// Trucking terminology — 6-language translations + inspector/driver conversation
// Source: terms.md (translations) + termsConvers.md (English conversations).
// convTrans holds the conversation translated into each non-English lang.

export const TERM_CATEGORIES = [
  { id: 'core_eld',     icon: '📱', name_en: 'Core ELD / HOS',          name_zh: '核心 ELD/HOS',  name_es: 'ELD / HOS básico',      name_hi: 'मुख्य ELD/HOS',   name_pa: 'ਮੁੱਖ ELD/HOS',     name_vi: 'ELD/HOS cốt lõi' },
  { id: 'hos',          icon: '⏱',  name_en: 'HOS Concepts',            name_zh: 'HOS 概念',       name_es: 'Conceptos HOS',         name_hi: 'HOS अवधारणाएं',  name_pa: 'HOS ਧਾਰਨਾਵਾਂ',     name_vi: 'Khái niệm HOS' },
  { id: 'duty_status',  icon: '🅿️', name_en: 'PC / Yard Move',          name_zh: 'PC / 场内移动',  name_es: 'PC / Yard Move',        name_hi: 'PC / यार्ड मूव',  name_pa: 'PC / ਯਾਰਡ ਮੂਵ',   name_vi: 'PC / Yard Move' },
  { id: 'inspection',   icon: '🔍', name_en: 'Inspection Actions',      name_zh: '检查动作',       name_es: 'Acciones de inspección', name_hi: 'निरीक्षण क्रियाएं', name_pa: 'ਜਾਂਚ ਕਿਰਿਆਵਾਂ',  name_vi: 'Hành động kiểm tra' },
  { id: 'legal_medical',icon: '⚕️', name_en: 'Legal / Medical',         name_zh: '法律/医疗',     name_es: 'Legal / Médico',        name_hi: 'कानूनी/चिकित्सीय', name_pa: 'ਕਾਨੂੰਨੀ/ਮੈਡੀਕਲ',   name_vi: 'Pháp lý / Y tế' },
  { id: 'documents',    icon: '📋', name_en: 'Documents / Permits',     name_zh: '文件/许可',     name_es: 'Documentos / Permisos', name_hi: 'दस्तावेज़/परमिट',  name_pa: 'ਦਸਤਾਵੇਜ਼/ਪਰਮਿਟ', name_vi: 'Tài liệu / Giấy phép' },
]

export const TERMS = [
  // ── Core ELD / HOS ───────────────────────────────────────
  { category: 'core_eld', en: 'ELD (Electronic Logging Device)', zh: '电子行车日志设备', vi: 'thiết bị ghi dữ liệu điện tử (ELD)', es: 'dispositivo de registro electrónico (ELD)', pa: 'ਇਲੈਕਟ੍ਰਾਨਿਕ ਲੋਗਿੰਗ ਡਿਵਾਈਸ (ELD)', hi: 'इलेक्ट्रॉनिक लॉगिंग डिवाइस (ELD)',
    inspector: 'Please show me your ELD so I can review your last 8 days of logs.',
    driver: 'Yes, inspector, here is my electronic logging device screen with my log history.',
    convTrans: {
      zh: { inspector: '请给我看你的电子行车日志设备，我要查看过去 8 天的记录。', driver: '好的，警官，这是我的 ELD 屏幕，上面有我的日志记录。' },
      vi: { inspector: 'Vui lòng cho tôi xem ELD của bạn để tôi xem lại 8 ngày nhật ký gần nhất.', driver: 'Vâng, thanh tra, đây là màn hình ELD với lịch sử nhật ký của tôi.' },
      es: { inspector: 'Muéstreme su ELD para revisar sus registros de los últimos 8 días.', driver: 'Sí, inspector, aquí está la pantalla de mi ELD con el historial de registros.' },
      pa: { inspector: 'ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਆਪਣਾ ELD ਦਿਖਾਓ ਤਾਂ ਜੋ ਮੈਂ ਪਿਛਲੇ 8 ਦਿਨਾਂ ਦੇ ਲੋਗ ਦੇਖ ਸਕਾਂ।', driver: 'ਹਾਂ ਸਾਹਬ, ਇਹ ਮੇਰੀ ELD ਸਕਰੀਨ ਹੈ ਜਿਸ ਉੱਤੇ ਮੇਰੇ ਲੋਗ ਹਨ।' },
      hi: { inspector: 'कृपया अपना ELD दिखाइए ताकि मैं पिछले 8 दिनों के लॉग देख सकूं।', driver: 'जी हाँ निरीक्षक, यह मेरी ELD स्क्रीन है जिसमें मेरा लॉग इतिहास है।' },
    } },
  { category: 'core_eld', en: 'Paper Log', zh: '纸质日志', vi: 'sổ nhật ký giấy', es: 'registro en papel', pa: 'ਕਾਗਜ਼ੀ ਲੋਗ', hi: 'पेपर लॉग / कागज़ी रिकॉर्ड',
    inspector: 'Why are you using a paper log instead of your ELD today?',
    driver: 'The ELD failed this morning, so I switched to a paper log to stay compliant.',
    convTrans: {
      zh: { inspector: '今天你为什么用纸质日志而不用 ELD？', driver: '今天早上 ELD 故障了，所以我改用纸质日志以保持合规。' },
      vi: { inspector: 'Hôm nay tại sao bạn dùng sổ giấy thay vì ELD?', driver: 'ELD bị hỏng sáng nay, nên tôi chuyển sang sổ nhật ký giấy để tuân thủ.' },
      es: { inspector: '¿Por qué está usando un registro en papel en lugar del ELD hoy?', driver: 'El ELD falló esta mañana, así que cambié al registro en papel para cumplir.' },
      pa: { inspector: 'ਅੱਜ ਤੁਸੀਂ ELD ਦੀ ਥਾਂ ਕਾਗਜ਼ੀ ਲੋਗ ਕਿਉਂ ਵਰਤ ਰਹੇ ਹੋ?', driver: 'ਸਵੇਰੇ ELD ਖਰਾਬ ਹੋ ਗਿਆ ਸੀ, ਇਸ ਲਈ ਮੈਂ ਨਿਯਮਾਂ ਮੁਤਾਬਕ ਕਾਗਜ਼ੀ ਲੋਗ ਵਰਤ ਰਿਹਾ ਹਾਂ।' },
      hi: { inspector: 'आज आप ELD की जगह कागज़ी लॉग क्यों इस्तेमाल कर रहे हैं?', driver: 'सुबह ELD खराब हो गया था, इसलिए मैंने नियमों का पालन करने के लिए पेपर लॉग पर स्विच कर लिया।' },
    } },
  { category: 'core_eld', en: 'Time Card', zh: '打卡记录', vi: 'thẻ chấm công', es: 'tarjeta de tiempo', pa: 'ਟਾਈਮ ਕਾਰਡ', hi: 'टाइम कार्ड',
    inspector: 'Do you normally record your local work on a time card?',
    driver: 'Yes, inspector, for local runs my company keeps a time card instead of a full logbook.',
    convTrans: {
      zh: { inspector: '你平常是不是用打卡记录来记录本地工作？', driver: '是的，警官，本地运输公司用打卡记录而不是完整日志本。' },
      vi: { inspector: 'Bạn có thường ghi công việc địa phương bằng thẻ chấm công không?', driver: 'Vâng, công ty tôi dùng thẻ chấm công cho các chuyến địa phương thay vì sổ nhật ký đầy đủ.' },
      es: { inspector: '¿Normalmente registra su trabajo local en una tarjeta de tiempo?', driver: 'Sí, inspector, para viajes locales mi empresa usa tarjeta de tiempo en lugar del libro completo.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਆਮ ਤੌਰ ਤੇ ਲੋਕਲ ਕੰਮ ਲਈ ਟਾਈਮ ਕਾਰਡ ਵਰਤਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਲੋਕਲ ਚੱਕਰਾਂ ਲਈ ਕੰਪਨੀ ਪੂਰੀ ਲੋਗ ਬੁੱਕ ਦੀ ਥਾਂ ਟਾਈਮ ਕਾਰਡ ਰੱਖਦੀ ਹੈ।' },
      hi: { inspector: 'क्या आप आमतौर पर लोकल काम के लिए टाइम कार्ड का इस्तेमाल करते हैं?', driver: 'जी हाँ, लोकल यात्राओं के लिए हमारी कंपनी पूरी लॉगबुक की जगह टाइम कार्ड रखती है।' },
    } },
  { category: 'core_eld', en: 'Graph Grid (log grid)', zh: '日志图表', vi: 'lưới đồ thị nhật ký', es: 'cuadrícula del gráfico de registro', pa: 'ਲਾਗ ਗ੍ਰਾਫ ਗਰਿੱਡ', hi: 'ग्राफ ग्रिड (लॉग चार्ट)',
    inspector: 'On your old logs, did you fill out the graph grid correctly each day?',
    driver: 'Yes, inspector, I drew my duty status on the graph grid for every 24-hour period.',
    convTrans: {
      zh: { inspector: '过去的日志上，你每天的图表是否填写正确？', driver: '是的，警官，我每 24 小时都在日志图表上画出了值勤状态。' },
      vi: { inspector: 'Trên các sổ nhật ký cũ, bạn có điền lưới đồ thị đúng mỗi ngày không?', driver: 'Vâng, tôi đã vẽ trạng thái làm việc lên lưới đồ thị cho mỗi 24 giờ.' },
      es: { inspector: 'En sus registros antiguos, ¿llenó la cuadrícula del gráfico correctamente cada día?', driver: 'Sí, inspector, dibujé mi estado de servicio en la cuadrícula para cada período de 24 horas.' },
      pa: { inspector: 'ਪੁਰਾਣੇ ਲੋਗਾਂ ਉੱਤੇ ਕੀ ਤੁਸੀਂ ਹਰ ਦਿਨ ਗ੍ਰਾਫ ਗਰਿੱਡ ਠੀਕ ਭਰਿਆ ਸੀ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਹਰ 24 ਘੰਟਿਆਂ ਲਈ ਆਪਣੀ ਡਿਊਟੀ ਸਟੇਟਸ ਗਰਿੱਡ ਉੱਤੇ ਵਾਹੀ ਸੀ।' },
      hi: { inspector: 'पुराने लॉग पर, क्या आपने हर दिन ग्राफ ग्रिड सही भरा था?', driver: 'जी हाँ निरीक्षक, मैंने हर 24 घंटे की अवधि के लिए ग्राफ ग्रिड पर अपनी ड्यूटी स्थिति दिखाई थी।' },
    } },
  { category: 'core_eld', en: 'Log Entry', zh: '日志条目', vi: 'mục ghi nhật ký', es: 'entrada de registro', pa: 'ਲੋਗ ਐਂਟਰੀ', hi: 'लॉग प्रविष्टि',
    inspector: 'When did you make the last log entry in your system?',
    driver: 'I created my last log entry when I went from off duty to driving at 7 a.m.',
    convTrans: {
      zh: { inspector: '你最后一次的日志条目是什么时候做的？', driver: '我最后一次的日志条目是早上 7 点从休息切换到驾驶时记录的。' },
      vi: { inspector: 'Lần cuối bạn ghi mục nhật ký vào hệ thống là khi nào?', driver: 'Tôi tạo mục ghi cuối cùng lúc 7 giờ sáng khi chuyển từ nghỉ sang lái xe.' },
      es: { inspector: '¿Cuándo hizo la última entrada de registro en su sistema?', driver: 'Hice mi última entrada cuando pasé de fuera de servicio a conducir a las 7 a. m.' },
      pa: { inspector: 'ਤੁਸੀਂ ਆਖਰੀ ਲੋਗ ਐਂਟਰੀ ਕਦੋਂ ਪਾਈ ਸੀ?', driver: 'ਸਵੇਰੇ 7 ਵਜੇ ਜਦੋਂ ਮੈਂ ਆਫ ਡਿਊਟੀ ਤੋਂ ਡ੍ਰਾਈਵਿੰਗ ਉੱਤੇ ਆਇਆ, ਉਦੋਂ ਮੈਂ ਆਖਰੀ ਲੋਗ ਐਂਟਰੀ ਕੀਤੀ ਸੀ।' },
      hi: { inspector: 'आपने अपनी सिस्टम में आख़िरी लॉग प्रविष्टि कब की थी?', driver: 'मैंने सुबह 7 बजे ऑफ ड्यूटी से ड्राइविंग पर जाते समय अपनी आख़िरी प्रविष्टि की थी।' },
    } },
  { category: 'core_eld', en: 'Transfer Data', zh: '传输数据', vi: 'chuyển dữ liệu', es: 'transferir datos', pa: 'ਡਾਟਾ ਟ੍ਰਾਂਸਫਰ ਕਰਨਾ', hi: 'डेटा स्थानांतरण',
    inspector: 'Can you transfer data from your ELD to my system now?',
    driver: 'Yes, inspector, I will use the transfer data option on the ELD menu.',
    convTrans: {
      zh: { inspector: '你能现在把 ELD 的数据传输到我的系统吗？', driver: '可以，警官，我会使用 ELD 菜单上的传输数据选项。' },
      vi: { inspector: 'Bạn có thể chuyển dữ liệu từ ELD sang hệ thống của tôi ngay không?', driver: 'Được, tôi sẽ dùng tùy chọn chuyển dữ liệu trong menu ELD.' },
      es: { inspector: '¿Puede transferir datos de su ELD a mi sistema ahora?', driver: 'Sí, inspector, usaré la opción de transferir datos del menú del ELD.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਹੁਣੇ ELD ਤੋਂ ਮੇਰੇ ਸਿਸਟਮ ਤੇ ਡਾਟਾ ਭੇਜ ਸਕਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ELD ਮੀਨੂ ਉੱਤੇ ਟ੍ਰਾਂਸਫਰ ਡਾਟਾ ਵਿਕਲਪ ਵਰਤਾਂਗਾ।' },
      hi: { inspector: 'क्या आप अभी अपने ELD से मेरे सिस्टम में डेटा ट्रांसफर कर सकते हैं?', driver: 'जी हाँ, मैं ELD मेन्यू में ट्रांसफर डेटा विकल्प का इस्तेमाल करूंगा।' },
    } },
  { category: 'core_eld', en: 'Web Service (data transfer)', zh: '网络服务传输', vi: 'dịch vụ web (truyền dữ liệu)', es: 'servicio web (transferencia de datos)', pa: 'ਵੈੱਬ ਸੇਵਾ ਰਾਹੀਂ ਡਾਟਾ ਭੇਜਣਾ', hi: 'वेब सेवा द्वारा डेटा ट्रांसफर',
    inspector: 'Is your ELD set up to send logs by web service?',
    driver: 'Yes, inspector, I can send my records directly to enforcement using web service.',
    convTrans: {
      zh: { inspector: '你的 ELD 是否设置了通过网络服务发送日志？', driver: '是的，警官，我可以用网络服务直接把记录发给执法部门。' },
      vi: { inspector: 'ELD của bạn có được cấu hình gửi nhật ký qua dịch vụ web không?', driver: 'Vâng, tôi có thể gửi hồ sơ trực tiếp đến cơ quan thực thi qua dịch vụ web.' },
      es: { inspector: '¿Su ELD está configurado para enviar registros por servicio web?', driver: 'Sí, inspector, puedo enviar mis registros directamente a las autoridades por servicio web.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡਾ ELD ਵੈੱਬ ਸੇਵਾ ਰਾਹੀਂ ਲੋਗ ਭੇਜਣ ਲਈ ਸੈੱਟ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਵੈੱਬ ਸੇਵਾ ਰਾਹੀਂ ਸਿੱਧਾ ਅਫ਼ਸਰਾਂ ਨੂੰ ਰਿਕਾਰਡ ਭੇਜ ਸਕਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आपका ELD वेब सेवा द्वारा लॉग भेजने के लिए सेट है?', driver: 'जी हाँ, मैं वेब सेवा से सीधे अधिकारियों को रिकॉर्ड भेज सकता हूँ।' },
    } },
  { category: 'core_eld', en: 'Email Transfer', zh: '邮件传输', vi: 'gửi dữ liệu qua email', es: 'envío por correo electrónico', pa: 'ਈਮੇਲ ਰਾਹੀਂ ਭੇਜਣਾ', hi: 'ईमेल द्वारा ट्रांसफर',
    inspector: 'If web service fails, can you do an email transfer of your logs?',
    driver: 'Yes, inspector, I can send an email transfer to the official address from my ELD.',
    convTrans: {
      zh: { inspector: '如果网络服务失败，你可以通过邮件传输日志吗？', driver: '可以，警官，我可以从 ELD 用邮件传输发送到官方地址。' },
      vi: { inspector: 'Nếu dịch vụ web hỏng, bạn có thể gửi nhật ký qua email không?', driver: 'Vâng, tôi có thể gửi qua email đến địa chỉ chính thức từ ELD.' },
      es: { inspector: 'Si falla el servicio web, ¿puede hacer un envío por correo electrónico de sus registros?', driver: 'Sí, inspector, puedo enviar un correo a la dirección oficial desde mi ELD.' },
      pa: { inspector: 'ਜੇ ਵੈੱਬ ਸੇਵਾ ਫੇਲ ਹੋ ਜਾਵੇ, ਕੀ ਤੁਸੀਂ ਈਮੇਲ ਰਾਹੀਂ ਲੋਗ ਭੇਜ ਸਕਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਆਪਣੇ ELD ਤੋਂ ਅਧਿਕਾਰਤ ਪਤੇ ਤੇ ਈਮੇਲ ਭੇਜ ਸਕਦਾ ਹਾਂ।' },
      hi: { inspector: 'अगर वेब सेवा फेल हो, तो क्या आप ईमेल से लॉग भेज सकते हैं?', driver: 'जी हाँ, मैं अपने ELD से अधिकारिक पते पर ईमेल भेज सकता हूँ।' },
    } },
  { category: 'core_eld', en: 'Malfunction', zh: '故障', vi: 'trục trặc / hỏng hóc', es: 'malfunción', pa: 'ਖਰਾਬੀ', hi: 'खराबी / खराब होना',
    inspector: 'You reported an ELD malfunction yesterday; is it fixed now?',
    driver: 'Yes, inspector, the malfunction was repaired and the unit is working correctly today.',
    convTrans: {
      zh: { inspector: '你昨天报告了 ELD 故障，现在修好了吗？', driver: '修好了，警官，故障已修复，今天设备运行正常。' },
      vi: { inspector: 'Hôm qua bạn báo ELD trục trặc, đã sửa xong chưa?', driver: 'Vâng, trục trặc đã được sửa và thiết bị hoạt động bình thường hôm nay.' },
      es: { inspector: 'Ayer reportó una malfunción del ELD; ¿ya está reparada?', driver: 'Sí, inspector, la malfunción se reparó y la unidad funciona bien hoy.' },
      pa: { inspector: 'ਤੁਸੀਂ ਕੱਲ੍ਹ ELD ਦੀ ਖਰਾਬੀ ਦੱਸੀ ਸੀ, ਕੀ ਹੁਣ ਠੀਕ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਖਰਾਬੀ ਠੀਕ ਹੋ ਗਈ ਹੈ ਤੇ ਯੂਨਿਟ ਅੱਜ ਸਹੀ ਚੱਲ ਰਿਹਾ ਹੈ।' },
      hi: { inspector: 'आपने कल ELD खराबी की रिपोर्ट दी थी; क्या अब ठीक हो गया?', driver: 'जी हाँ निरीक्षक, खराबी ठीक हो गई है और आज यूनिट सही चल रही है।' },
    } },
  { category: 'core_eld', en: 'Backup Paper Logs', zh: '备用纸质日志', vi: 'sổ nhật ký giấy dự phòng', es: 'registros en papel de respaldo', pa: 'ਬੈਕਅੱਪ ਕਾਗਜ਼ੀ ਲੋਗ', hi: 'बैकअप पेपर लॉग',
    inspector: 'Show me your backup paper logs in case the ELD stops working again.',
    driver: 'Here they are, inspector; I keep several backup paper logs in my permit book.',
    convTrans: {
      zh: { inspector: '给我看你的备用纸质日志，以防 ELD 再次停机。', driver: '在这里，警官，我在证件夹里放了几份备用纸质日志。' },
      vi: { inspector: 'Cho tôi xem sổ nhật ký giấy dự phòng phòng khi ELD lại hỏng.', driver: 'Đây ạ, tôi giữ vài cuốn nhật ký giấy dự phòng trong sổ giấy phép.' },
      es: { inspector: 'Muéstreme sus registros en papel de respaldo por si el ELD deja de funcionar.', driver: 'Aquí están, inspector; guardo varios registros en papel de respaldo en mi libro de permisos.' },
      pa: { inspector: 'ਜੇ ELD ਫਿਰ ਬੰਦ ਹੋ ਜਾਵੇ, ਮੈਨੂੰ ਆਪਣੇ ਬੈਕਅੱਪ ਕਾਗਜ਼ੀ ਲੋਗ ਦਿਖਾਓ।', driver: 'ਇਹ ਰਹੇ ਸਾਹਬ, ਮੈਂ ਆਪਣੀ ਪਰਮਿਟ ਬੁੱਕ ਵਿੱਚ ਕਈ ਬੈਕਅੱਪ ਕਾਗਜ਼ੀ ਲੋਗ ਰੱਖਦਾ ਹਾਂ।' },
      hi: { inspector: 'ELD फिर बंद हो जाए तो मुझे अपने बैकअप पेपर लॉग दिखाइए।', driver: 'ये रहे, निरीक्षक; मैं अपनी परमिट बुक में कई बैकअप पेपर लॉग रखता हूँ।' },
    } },
  { category: 'core_eld', en: '8 Days of Paper Logs', zh: '8天纸质日志记录', vi: '8 ngày nhật ký giấy', es: '8 días de registros en papel', pa: '8 ਦਿਨਾਂ ਦੇ ਕਾਗਜ਼ੀ ਲੋਗ', hi: '8 दिनों के पेपर लॉग',
    inspector: 'Regulations require at least 8 days of paper logs in the truck; do you have them?',
    driver: 'Yes, inspector, I have more than 8 days of blank paper logs ready to use.',
    convTrans: {
      zh: { inspector: '法规要求车上至少有 8 天纸质日志，你有吗？', driver: '有的，警官，我备有超过 8 天的空白纸质日志。' },
      vi: { inspector: 'Quy định yêu cầu ít nhất 8 ngày nhật ký giấy trên xe; bạn có chưa?', driver: 'Vâng, tôi có hơn 8 ngày sổ giấy trắng sẵn sàng dùng.' },
      es: { inspector: 'La normativa exige al menos 8 días de registros en papel en el camión; ¿los tiene?', driver: 'Sí, inspector, tengo más de 8 días de registros en blanco listos para usar.' },
      pa: { inspector: 'ਨਿਯਮ ਮੁਤਾਬਕ ਟਰੱਕ ਵਿੱਚ ਘੱਟੋ-ਘੱਟ 8 ਦਿਨ ਕਾਗਜ਼ੀ ਲੋਗ ਚਾਹੀਦੇ ਹਨ; ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਹਨ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰੇ ਕੋਲ 8 ਦਿਨਾਂ ਤੋਂ ਵੱਧ ਖਾਲੀ ਕਾਗਜ਼ੀ ਲੋਗ ਤਿਆਰ ਹਨ।' },
      hi: { inspector: 'नियमों के तहत ट्रक में कम से कम 8 दिनों के पेपर लॉग चाहिए; क्या आपके पास हैं?', driver: 'जी हाँ, मेरे पास 8 दिनों से ज़्यादा खाली पेपर लॉग तैयार हैं।' },
    } },
  { category: 'core_eld', en: 'ELD Instruction Manual', zh: 'ELD操作手册', vi: 'sổ hướng dẫn ELD', es: 'manual de instrucciones del ELD', pa: 'ELD ਹਦਾਇਤ ਮੈਨੂਅਲ', hi: 'ELD निर्देश पुस्तिका',
    inspector: 'Where do you keep the ELD instruction manual in this cab?',
    driver: 'The ELD instruction manual is in this side pocket, inspector.',
    convTrans: {
      zh: { inspector: '你把 ELD 操作手册放在驾驶室哪里？', driver: 'ELD 操作手册在这个侧袋里，警官。' },
      vi: { inspector: 'Bạn để sổ hướng dẫn ELD ở đâu trong cabin?', driver: 'Sổ hướng dẫn ELD nằm trong túi bên này, thưa thanh tra.' },
      es: { inspector: '¿Dónde guarda el manual del ELD en esta cabina?', driver: 'El manual del ELD está en este bolsillo lateral, inspector.' },
      pa: { inspector: 'ਤੁਸੀਂ ਇਸ ਕੈਬ ਵਿੱਚ ELD ਮੈਨੂਅਲ ਕਿੱਥੇ ਰੱਖਦੇ ਹੋ?', driver: 'ELD ਮੈਨੂਅਲ ਇਸ ਸਾਈਡ ਜੇਬ ਵਿੱਚ ਹੈ, ਸਾਹਬ।' },
      hi: { inspector: 'इस केबिन में ELD निर्देश पुस्तिका कहाँ रखते हैं?', driver: 'ELD मैन्युअल इस साइड पॉकेट में है, निरीक्षक।' },
    } },

  // ── HOS Concepts ─────────────────────────────────────────
  { category: 'hos', en: 'HOS (Hours of Service)', zh: '工作时间规定', vi: 'quy định giờ làm việc / giờ lái xe', es: 'horas de servicio (HOS)', pa: 'ਡਿਊਟੀ ਘੰਟੇ / Hours of Service', hi: 'सेवा के घंटे (HOS)',
    inspector: 'Are you familiar with the basic HOS, or Hours of Service, rules?',
    driver: 'Yes, inspector, I follow the Hours of Service limits every day.',
    convTrans: {
      zh: { inspector: '你熟悉基本的 HOS 工作时间规定吗？', driver: '熟悉，警官，我每天都遵守工作时间规定。' },
      vi: { inspector: 'Bạn có nắm các quy định HOS cơ bản không?', driver: 'Vâng, mỗi ngày tôi đều tuân thủ giới hạn giờ làm việc.' },
      es: { inspector: '¿Conoce las reglas básicas de HOS, las horas de servicio?', driver: 'Sí, inspector, sigo los límites de horas de servicio todos los días.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਮੁੱਢਲੇ HOS (ਡਿਊਟੀ ਘੰਟਿਆਂ) ਦੇ ਨਿਯਮ ਜਾਣਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਹਰ ਦਿਨ HOS ਸੀਮਾਵਾਂ ਦਾ ਪਾਲਣ ਕਰਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आप बुनियादी HOS (सेवा घंटे) नियम जानते हैं?', driver: 'जी हाँ निरीक्षक, मैं हर दिन सेवा के घंटे सीमाओं का पालन करता हूँ।' },
    } },
  { category: 'hos', en: '11-Hour Driving Limit', zh: '11小时驾驶上限', vi: 'giới hạn lái 11 giờ', es: 'límite de conducción de 11 horas', pa: '11 ਘੰਟੇ ਡ੍ਰਾਈਵਿੰਗ ਸੀਮਾ', hi: '11 घंटे ड्राइविंग सीमा',
    inspector: 'How many hours have you driven today under the 11-hour driving limit?',
    driver: 'I have driven 6 hours so far, inspector, so I am under the 11-hour driving limit.',
    convTrans: {
      zh: { inspector: '在 11 小时驾驶上限内，你今天已经开了多少小时？', driver: '我今天开了 6 小时，警官，还在 11 小时上限以内。' },
      vi: { inspector: 'Hôm nay bạn đã lái bao nhiêu giờ trong giới hạn 11 giờ?', driver: 'Tôi đã lái 6 giờ, vẫn dưới giới hạn 11 giờ.' },
      es: { inspector: '¿Cuántas horas ha conducido hoy dentro del límite de 11 horas?', driver: 'He conducido 6 horas, inspector, así que estoy dentro del límite de 11 horas.' },
      pa: { inspector: '11 ਘੰਟੇ ਡ੍ਰਾਈਵਿੰਗ ਸੀਮਾ ਅੰਦਰ ਤੁਸੀਂ ਅੱਜ ਕਿੰਨੇ ਘੰਟੇ ਚਲਾਏ?', driver: 'ਮੈਂ ਹੁਣ ਤੱਕ 6 ਘੰਟੇ ਚਲਾਏ ਹਨ, ਯਾਨੀ 11 ਘੰਟੇ ਸੀਮਾ ਤੋਂ ਘੱਟ।' },
      hi: { inspector: '11 घंटे की ड्राइविंग सीमा के अंदर आज आपने कितने घंटे चलाया?', driver: 'मैंने अब तक 6 घंटे चलाया है, यानी 11 घंटे सीमा से कम।' },
    } },
  { category: 'hos', en: '14-Hour Window', zh: '14小时工作窗口', vi: 'khung 14 giờ làm việc', es: 'ventana de 14 horas', pa: '14 ਘੰਟਿਆਂ ਦੀ ਡਿਊਟੀ ਵਿੰਡੋ', hi: '14 घंटे की कार्य अवधि',
    inspector: 'What time did your 14-hour window start this morning?',
    driver: 'It started at 5 a.m., inspector, so my 14-hour window ends at 7 p.m.',
    convTrans: {
      zh: { inspector: '你今天的 14 小时工作窗口几点开始的？', driver: '早上 5 点开始的，警官，所以 14 小时窗口在晚上 7 点结束。' },
      vi: { inspector: 'Khung 14 giờ làm việc của bạn bắt đầu lúc mấy giờ sáng nay?', driver: 'Bắt đầu lúc 5 giờ sáng, nên kết thúc lúc 7 giờ tối.' },
      es: { inspector: '¿A qué hora comenzó su ventana de 14 horas esta mañana?', driver: 'Comenzó a las 5 a. m., inspector, así que termina a las 7 p. m.' },
      pa: { inspector: 'ਤੁਹਾਡੀ 14 ਘੰਟੇ ਡਿਊਟੀ ਵਿੰਡੋ ਅੱਜ ਸਵੇਰੇ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਈ?', driver: 'ਸਵੇਰੇ 5 ਵਜੇ ਸ਼ੁਰੂ ਹੋਈ, ਸੋ ਸ਼ਾਮ 7 ਵਜੇ ਖਤਮ ਹੋਵੇਗੀ।' },
      hi: { inspector: 'आज सुबह आपकी 14 घंटे की अवधि कब शुरू हुई?', driver: 'सुबह 5 बजे शुरू हुई, इसलिए 14 घंटे की अवधि शाम 7 बजे ख़त्म होगी।' },
    } },
  { category: 'hos', en: '30-Minute Break', zh: '30分钟休息', vi: 'nghỉ 30 phút', es: 'pausa de 30 minutos', pa: '30 ਮਿੰਟ ਵਿਸ਼ਰਾਮ', hi: '30 मिनट का ब्रेक',
    inspector: 'When did you take your required 30-minute break today?',
    driver: 'I took a 30-minute break at noon, inspector, after about 6 hours of driving.',
    convTrans: {
      zh: { inspector: '你今天的 30 分钟休息是什么时候休的？', driver: '中午休息了 30 分钟，警官，开了大约 6 小时之后。' },
      vi: { inspector: 'Hôm nay bạn nghỉ 30 phút lúc nào?', driver: 'Tôi nghỉ 30 phút lúc trưa, sau khoảng 6 giờ lái xe.' },
      es: { inspector: '¿Cuándo tomó su pausa obligatoria de 30 minutos hoy?', driver: 'Tomé la pausa de 30 minutos al mediodía, después de unas 6 horas conduciendo.' },
      pa: { inspector: 'ਅੱਜ ਤੁਸੀਂ ਆਪਣਾ 30 ਮਿੰਟ ਵਾਲਾ ਵਿਸ਼ਰਾਮ ਕਦੋਂ ਲਿਆ?', driver: 'ਮੈਂ ਦੁਪਹਿਰ 12 ਵਜੇ 30 ਮਿੰਟ ਆਰਾਮ ਕੀਤਾ, ਲਗਭਗ 6 ਘੰਟੇ ਚਲਾਉਣ ਤੋਂ ਬਾਅਦ।' },
      hi: { inspector: 'आज आपने 30 मिनट का अनिवार्य ब्रेक कब लिया?', driver: 'मैंने दोपहर में 30 मिनट का ब्रेक लिया, करीब 6 घंटे चलाने के बाद।' },
    } },
  { category: 'hos', en: '70-Hour / 8-Day Cycle', zh: '70小时/8天周期', vi: 'chu kỳ 70 giờ / 8 ngày', es: 'ciclo de 70 horas / 8 días', pa: '70 ਘੰਟੇ / 8 ਦਿਨ ਚੱਕਰ', hi: '70 घंटे / 8 दिन चक्र',
    inspector: 'How many hours are left on your 70-hour/8-day cycle?',
    driver: 'I have 10 hours left in my 70-hour/8-day cycle, inspector.',
    convTrans: {
      zh: { inspector: '你 70 小时/8 天周期还剩多少小时？', driver: '我还剩 10 小时，警官。' },
      vi: { inspector: 'Bạn còn bao nhiêu giờ trong chu kỳ 70 giờ / 8 ngày?', driver: 'Tôi còn 10 giờ, thưa thanh tra.' },
      es: { inspector: '¿Cuántas horas le quedan en su ciclo de 70 horas / 8 días?', driver: 'Me quedan 10 horas, inspector.' },
      pa: { inspector: 'ਤੁਹਾਡੇ 70 ਘੰਟੇ / 8 ਦਿਨ ਚੱਕਰ ਵਿੱਚ ਕਿੰਨੇ ਘੰਟੇ ਬਾਕੀ ਹਨ?', driver: 'ਮੇਰੇ ਚੱਕਰ ਵਿੱਚ 10 ਘੰਟੇ ਬਾਕੀ ਹਨ, ਸਾਹਬ।' },
      hi: { inspector: 'आपके 70 घंटे / 8 दिन के चक्र में कितने घंटे बचे हैं?', driver: 'मेरे चक्र में 10 घंटे बचे हैं, निरीक्षक।' },
    } },
  { category: 'hos', en: 'On Duty', zh: '值勤状态', vi: 'đang làm việc (on duty)', es: 'en servicio', pa: 'ਡਿਊਟੀ ਤੇ', hi: 'ड्यूटी पर (ऑन ड्यूटी)',
    inspector: 'At what time did you first go on duty this morning?',
    driver: 'I went on duty at 6 a.m., inspector, when I started my pre-trip inspection.',
    convTrans: {
      zh: { inspector: '今天早上你几点开始值勤？', driver: '我早上 6 点开始值勤的，警官，那时开始做车前检查。' },
      vi: { inspector: 'Sáng nay mấy giờ bạn bắt đầu làm việc?', driver: 'Tôi bắt đầu làm việc lúc 6 giờ sáng khi kiểm tra trước chuyến.' },
      es: { inspector: '¿A qué hora se puso en servicio esta mañana?', driver: 'Me puse en servicio a las 6 a. m. cuando empecé la inspección previa.' },
      pa: { inspector: 'ਅੱਜ ਸਵੇਰੇ ਤੁਸੀਂ ਪਹਿਲੀ ਵਾਰ ਡਿਊਟੀ ਉੱਤੇ ਕਦੋਂ ਆਏ?', driver: 'ਮੈਂ ਸਵੇਰੇ 6 ਵਜੇ ਡਿਊਟੀ ਤੇ ਆਇਆ, ਜਦੋਂ ਪ੍ਰੀ-ਟ੍ਰਿਪ ਜਾਂਚ ਸ਼ੁਰੂ ਕੀਤੀ।' },
      hi: { inspector: 'आज सुबह आप पहली बार कब ड्यूटी पर आए?', driver: 'मैं सुबह 6 बजे ड्यूटी पर आया, जब मैंने प्री-ट्रिप जांच शुरू की।' },
    } },
  { category: 'hos', en: 'Off Duty', zh: '休息状态', vi: 'nghỉ (off duty)', es: 'fuera de servicio / fuera de turno', pa: 'ਆਫ ਡਿਊਟੀ / ਛੁੱਟੀ', hi: 'ड्यूटी से बाहर (ऑफ ड्यूटी)',
    inspector: 'How many hours were you off duty last night?',
    driver: 'I was off duty for 10 full hours, inspector, before I started work today.',
    convTrans: {
      zh: { inspector: '昨晚你休息了多少小时？', driver: '昨晚我休息了完整的 10 小时，警官，今天才开始工作。' },
      vi: { inspector: 'Đêm qua bạn nghỉ bao nhiêu giờ?', driver: 'Tôi nghỉ trọn 10 giờ trước khi bắt đầu làm hôm nay.' },
      es: { inspector: '¿Cuántas horas estuvo fuera de servicio anoche?', driver: 'Estuve fuera de servicio 10 horas completas antes de empezar hoy.' },
      pa: { inspector: 'ਰਾਤ ਤੁਸੀਂ ਕਿੰਨੇ ਘੰਟੇ ਆਫ ਡਿਊਟੀ ਰਹੇ?', driver: 'ਅੱਜ ਕੰਮ ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਮੈਂ ਪੂਰੇ 10 ਘੰਟੇ ਆਫ ਡਿਊਟੀ ਸੀ।' },
      hi: { inspector: 'पिछली रात आप कितने घंटे ऑफ ड्यूटी थे?', driver: 'आज काम शुरू करने से पहले मैं पूरे 10 घंटे ऑफ ड्यूटी था।' },
    } },
  { category: 'hos', en: 'Sleeper Berth', zh: '卧铺状态', vi: 'giường nằm / chế độ cabin ngủ', es: 'litera (sleeper berth)', pa: 'ਸਲੀਪਰ ਬਰਥ', hi: 'स्लीपर बर्थ',
    inspector: 'Did you spend part of your break in the sleeper berth?',
    driver: 'Yes, inspector, I slept 8 hours in the sleeper berth last night.',
    convTrans: {
      zh: { inspector: '你休息时有一部分时间在卧铺里吗？', driver: '是的，警官，昨晚我在卧铺里睡了 8 小时。' },
      vi: { inspector: 'Bạn có nghỉ một phần trên giường nằm không?', driver: 'Vâng, đêm qua tôi ngủ 8 giờ trên giường nằm.' },
      es: { inspector: '¿Pasó parte de su descanso en la litera?', driver: 'Sí, inspector, dormí 8 horas en la litera anoche.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਆਪਣੇ ਆਰਾਮ ਦਾ ਹਿੱਸਾ ਸਲੀਪਰ ਬਰਥ ਵਿੱਚ ਬਿਤਾਇਆ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਰਾਤ ਸਲੀਪਰ ਬਰਥ ਵਿੱਚ 8 ਘੰਟੇ ਸੁੱਤਾ।' },
      hi: { inspector: 'क्या आपने अपने ब्रेक का कुछ हिस्सा स्लीपर बर्थ में बिताया?', driver: 'जी हाँ, मैंने पिछली रात स्लीपर बर्थ में 8 घंटे नींद ली।' },
    } },
  { category: 'hos', en: 'Driving Status', zh: '驾驶状态', vi: 'trạng thái đang lái', es: 'estado de conducción', pa: 'ਡ੍ਰਾਈਵਿੰਗ ਸਟੇਟਸ', hi: 'ड्राइविंग स्थिति',
    inspector: 'Your ELD shows you in driving status for this period; is that correct?',
    driver: 'Yes, inspector, I was moving the truck the whole time, so driving status is correct.',
    convTrans: {
      zh: { inspector: '你的 ELD 显示这段时间你在驾驶状态，对吗？', driver: '是的，警官，这段时间我一直在开车，驾驶状态是正确的。' },
      vi: { inspector: 'ELD báo bạn đang ở trạng thái lái trong khoảng này; đúng không?', driver: 'Vâng, suốt thời gian đó tôi đều lái xe, trạng thái đúng.' },
      es: { inspector: 'Su ELD muestra estado de conducción en este período; ¿es correcto?', driver: 'Sí, inspector, estuve conduciendo todo el tiempo, así que el estado es correcto.' },
      pa: { inspector: 'ਤੁਹਾਡਾ ELD ਇਸ ਸਮੇਂ ਡ੍ਰਾਈਵਿੰਗ ਸਟੇਟਸ ਦਿਖਾ ਰਿਹਾ ਹੈ; ਸਹੀ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਸਾਰਾ ਸਮਾਂ ਟਰੱਕ ਚਲਾ ਰਿਹਾ ਸੀ, ਸਟੇਟਸ ਸਹੀ ਹੈ।' },
      hi: { inspector: 'आपका ELD इस समय ड्राइविंग स्थिति दिखाता है; क्या यह सही है?', driver: 'जी हाँ निरीक्षक, मैं पूरे समय ट्रक चला रहा था, स्थिति सही है।' },
    } },
  { category: 'hos', en: 'Remaining Hours', zh: '剩余小时', vi: 'giờ còn lại', es: 'horas restantes', pa: 'ਬਾਕੀ ਘੰਟੇ', hi: 'बचे हुए घंटे',
    inspector: 'How many remaining hours of drive time do you have today?',
    driver: 'My ELD shows I have 3 remaining hours of driving, inspector.',
    convTrans: {
      zh: { inspector: '你今天还有多少剩余驾驶时间？', driver: '我的 ELD 显示还有 3 小时驾驶时间，警官。' },
      vi: { inspector: 'Hôm nay bạn còn lại bao nhiêu giờ lái xe?', driver: 'ELD báo tôi còn 3 giờ lái, thưa thanh tra.' },
      es: { inspector: '¿Cuántas horas le quedan de conducción hoy?', driver: 'Mi ELD muestra 3 horas restantes de conducción, inspector.' },
      pa: { inspector: 'ਅੱਜ ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨੇ ਘੰਟੇ ਡ੍ਰਾਈਵ ਟਾਈਮ ਬਾਕੀ ਹੈ?', driver: 'ਮੇਰਾ ELD ਦੱਸਦਾ ਹੈ ਕਿ 3 ਘੰਟੇ ਡ੍ਰਾਈਵਿੰਗ ਬਾਕੀ ਹਨ, ਸਾਹਬ।' },
      hi: { inspector: 'आज आपके पास कितने घंटे ड्राइव टाइम बचे हैं?', driver: 'मेरा ELD दिखाता है कि 3 घंटे ड्राइविंग बाकी है, निरीक्षक।' },
    } },
  { category: 'hos', en: 'Violation', zh: '违规', vi: 'vi phạm', es: 'infracción', pa: 'ਉਲੰਘਣਾ', hi: 'उल्लंघन',
    inspector: 'Do you see this HOS violation on your log from two days ago?',
    driver: 'Yes, inspector, I understand there is a violation and I will be more careful.',
    convTrans: {
      zh: { inspector: '你看到两天前日志上的这条 HOS 违规了吗？', driver: '看到了，警官，我明白有违规，以后会更小心。' },
      vi: { inspector: 'Bạn có thấy vi phạm HOS trên nhật ký hai ngày trước không?', driver: 'Vâng, tôi hiểu có vi phạm và sẽ cẩn thận hơn.' },
      es: { inspector: '¿Ve esta infracción de HOS en su registro de hace dos días?', driver: 'Sí, inspector, entiendo que hay una infracción y seré más cuidadoso.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਦੋ ਦਿਨ ਪਹਿਲਾਂ ਦੇ ਲੋਗ ਉੱਤੇ ਇਹ HOS ਉਲੰਘਣਾ ਵੇਖਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਸਮਝਦਾ ਹਾਂ ਕਿ ਉਲੰਘਣਾ ਹੈ ਤੇ ਅੱਗੇ ਤੋਂ ਜ਼ਿਆਦਾ ਧਿਆਨ ਰੱਖਾਂਗਾ।' },
      hi: { inspector: 'क्या आप दो दिन पहले के लॉग पर यह HOS उल्लंघन देखते हैं?', driver: 'जी हाँ निरीक्षक, मुझे पता है कि उल्लंघन है, मैं आगे से अधिक सावधान रहूँगा।' },
    } },
  { category: 'hos', en: 'Out of Service (OOS)', zh: '停运', vi: 'ngừng hoạt động / bị cấm chạy', es: 'fuera de servicio (OOS)', pa: 'ਆਉਟ ਆਫ ਸਰਵਿਸ', hi: 'सेवा से बाहर (OOS)',
    inspector: 'Because of this serious issue, I must place you out of service.',
    driver: 'I understand, inspector; while I am out of service I will not move the truck.',
    convTrans: {
      zh: { inspector: '因为这个严重问题，我必须把你列为停运。', driver: '我明白，警官，在停运期间我不会移动这辆卡车。' },
      vi: { inspector: 'Vì vấn đề nghiêm trọng này, tôi phải đặt bạn vào diện ngừng hoạt động.', driver: 'Tôi hiểu, trong thời gian ngừng hoạt động tôi sẽ không di chuyển xe.' },
      es: { inspector: 'Debido a este problema grave, debo ponerlo fuera de servicio.', driver: 'Entiendo, inspector; mientras esté fuera de servicio no moveré el camión.' },
      pa: { inspector: 'ਇਸ ਗੰਭੀਰ ਮਸਲੇ ਕਾਰਨ ਮੈਨੂੰ ਤੁਹਾਨੂੰ ਆਉਟ ਆਫ ਸਰਵਿਸ ਕਰਨਾ ਪਵੇਗਾ।', driver: 'ਸਮਝ ਗਿਆ ਸਾਹਬ; ਆਉਟ ਆਫ ਸਰਵਿਸ ਦੌਰਾਨ ਮੈਂ ਟਰੱਕ ਨਹੀਂ ਚਲਾਵਾਂਗਾ।' },
      hi: { inspector: 'इस गंभीर समस्या के कारण मुझे आपको सेवा से बाहर करना होगा।', driver: 'मैं समझता हूँ निरीक्षक; सेवा से बाहर रहते हुए मैं ट्रक नहीं चलाऊंगा।' },
    } },

  // ── Special Duty Statuses ────────────────────────────────
  { category: 'duty_status', en: 'Personal Conveyance (PC)', zh: '私用驾驶模式', vi: 'chế độ di chuyển cá nhân (PC)', es: 'uso personal del vehículo (PC)', pa: 'ਪਰਸਨਲ ਕਨਵੇਅੰਸ ਮੋਡ', hi: 'पर्सनल कन्‍वेयंस (PC)',
    inspector: 'Did you use Personal Conveyance to drive from the receiver to this truck stop?',
    driver: 'Yes, inspector, I was empty and off duty, so I used Personal Conveyance.',
    convTrans: {
      zh: { inspector: '你是不是用私用驾驶模式从收货方开到这个卡车站？', driver: '是的，警官，那时是空车且休息状态，所以用了私用驾驶模式。' },
      vi: { inspector: 'Bạn có dùng chế độ di chuyển cá nhân từ nơi nhận hàng đến trạm này không?', driver: 'Vâng, lúc đó xe trống và đang nghỉ, nên tôi dùng PC.' },
      es: { inspector: '¿Usó Uso Personal para conducir desde el receptor hasta este parador?', driver: 'Sí, inspector, iba vacío y fuera de servicio, así que usé Uso Personal.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਪ੍ਰਾਪਤਕਰਤਾ ਤੋਂ ਇਸ ਟਰੱਕ ਸਟਾਪ ਤੱਕ ਪਰਸਨਲ ਕਨਵੇਅੰਸ ਵਰਤੀ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਖਾਲੀ ਤੇ ਆਫ ਡਿਊਟੀ ਸੀ, ਇਸ ਲਈ ਪਰਸਨਲ ਕਨਵੇਅੰਸ ਵਰਤੀ।' },
      hi: { inspector: 'क्या आपने रिसीवर से इस ट्रक स्टॉप तक पर्सनल कन्वेयंस का इस्तेमाल किया?', driver: 'जी हाँ निरीक्षक, मैं खाली और ऑफ ड्यूटी था, इसलिए पर्सनल कन्वेयंस इस्तेमाल किया।' },
    } },
  { category: 'duty_status', en: 'Yard Move (YM)', zh: '场内移动模式', vi: 'di chuyển trong bãi (YM)', es: 'movimiento en patio (YM)', pa: 'ਯਾਰਡ ਮੂਵ ਮੋਡ', hi: 'यार्ड मूव (YM)',
    inspector: 'Why is this move marked as Yard Move on your log?',
    driver: 'Inspector, I used Yard Move because I was just repositioning the truck inside the yard.',
    convTrans: {
      zh: { inspector: '这次移动为什么在日志上标为场内移动？', driver: '警官，因为我只是在场内调整卡车位置，所以使用了场内移动模式。' },
      vi: { inspector: 'Tại sao lần di chuyển này lại đánh dấu là Yard Move trên nhật ký?', driver: 'Thưa thanh tra, vì tôi chỉ đổi vị trí xe trong bãi nên dùng Yard Move.' },
      es: { inspector: '¿Por qué este movimiento está marcado como Yard Move en su registro?', driver: 'Inspector, usé Yard Move porque solo estaba reubicando el camión dentro del patio.' },
      pa: { inspector: 'ਇਹ ਹਿਲਜੁਲ ਲੋਗ ਉੱਤੇ ਯਾਰਡ ਮੂਵ ਕਿਉਂ ਮਾਰਕ ਹੈ?', driver: 'ਸਾਹਬ, ਮੈਂ ਸਿਰਫ ਯਾਰਡ ਅੰਦਰ ਟਰੱਕ ਦੀ ਜਗ੍ਹਾ ਬਦਲ ਰਿਹਾ ਸੀ, ਇਸ ਲਈ ਯਾਰਡ ਮੂਵ ਵਰਤੀ।' },
      hi: { inspector: 'यह मूव आपके लॉग पर यार्ड मूव क्यों चिह्नित है?', driver: 'निरीक्षक, मैं केवल यार्ड के अंदर ट्रक को रिपोज़िशन कर रहा था, इसलिए यार्ड मूव इस्तेमाल किया।' },
    } },
  { category: 'duty_status', en: 'Unassigned Driving Time', zh: '未分配驾驶时间', vi: 'thời gian lái xe chưa gán', es: 'tiempo de conducción no asignado', pa: 'ਅਣ-ਸੌਂਪਿਆ ਡ੍ਰਾਈਵਿੰਗ ਸਮਾਂ', hi: 'असाइन न किया गया ड्राइविंग समय',
    inspector: 'There is unassigned driving time on this truck; can you explain it?',
    driver: 'Yes, inspector, I forgot to log in that morning, so the driving shows as unassigned driving time.',
    convTrans: {
      zh: { inspector: '这辆车上有未分配的驾驶时间，你能解释吗？', driver: '可以，警官，那天早上我忘了登录，所以驾驶显示为未分配驾驶时间。' },
      vi: { inspector: 'Trên xe này có thời gian lái chưa gán; bạn giải thích được không?', driver: 'Vâng, sáng đó tôi quên đăng nhập, nên thời gian lái hiện chưa gán.' },
      es: { inspector: 'Hay tiempo de conducción no asignado en este camión; ¿puede explicarlo?', driver: 'Sí, inspector, esa mañana olvidé iniciar sesión, por eso aparece como no asignado.' },
      pa: { inspector: 'ਇਸ ਟਰੱਕ ਉੱਤੇ ਅਣ-ਸੌਂਪਿਆ ਡ੍ਰਾਈਵਿੰਗ ਸਮਾਂ ਹੈ; ਤੁਸੀਂ ਸਮਝਾ ਸਕਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਉਸ ਸਵੇਰ ਲੌਗ ਇਨ ਕਰਨਾ ਭੁੱਲ ਗਿਆ ਸੀ, ਇਸ ਲਈ ਅਣ-ਸੌਂਪਿਆ ਦਿਖ ਰਿਹਾ ਹੈ।' },
      hi: { inspector: 'इस ट्रक पर असाइन न किया गया ड्राइविंग समय है; क्या समझा सकते हैं?', driver: 'जी हाँ निरीक्षक, उस सुबह मैं लॉग इन करना भूल गया था, इसलिए असाइन न किया हुआ दिख रहा है।' },
    } },
  { category: 'duty_status', en: 'Edit Log', zh: '编辑日志', vi: 'chỉnh sửa nhật ký', es: 'editar el registro', pa: 'ਲੋਗ ਸੋਧਣਾ', hi: 'लॉग संपादित करना',
    inspector: 'Did you edit your log when you realized the status was wrong?',
    driver: 'Yes, inspector, I used the edit log function and added a note about the mistake.',
    convTrans: {
      zh: { inspector: '当你发现状态错误时，你编辑了日志吗？', driver: '编辑了，警官，我用了编辑日志功能并添加了错误说明。' },
      vi: { inspector: 'Khi nhận ra trạng thái sai, bạn có chỉnh sửa nhật ký không?', driver: 'Vâng, tôi đã dùng chức năng chỉnh sửa và thêm ghi chú về lỗi.' },
      es: { inspector: '¿Editó su registro al darse cuenta de que el estado estaba mal?', driver: 'Sí, inspector, usé la función de editar registro y agregué una nota sobre el error.' },
      pa: { inspector: 'ਜਦੋਂ ਤੁਸੀਂ ਸਟੇਟਸ ਗਲਤ ਵੇਖਿਆ, ਕੀ ਤੁਸੀਂ ਲੋਗ ਸੋਧਿਆ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਐਡਿਟ ਲੋਗ ਫੰਕਸ਼ਨ ਵਰਤਿਆ ਤੇ ਗਲਤੀ ਦਾ ਨੋਟ ਲਿਖਿਆ।' },
      hi: { inspector: 'जब आपको स्थिति गलत मिली, क्या आपने लॉग संपादित किया?', driver: 'जी हाँ निरीक्षक, मैंने एडिट लॉग का इस्तेमाल किया और गलती की नोट जोड़ी।' },
    } },
  { category: 'duty_status', en: 'Certify Logs', zh: '认证日志', vi: 'xác nhận nhật ký', es: 'certificar los registros', pa: 'ਲੋਗ ਪ੍ਰਮਾਣਿਤ ਕਰਨਾ', hi: 'लॉग प्रमाणित करना',
    inspector: 'Have you certified your logs for the last seven days?',
    driver: 'Yes, inspector, I certify logs at the end of each day as true and correct.',
    convTrans: {
      zh: { inspector: '过去七天的日志你都认证了吗？', driver: '都认证了，警官，我每天结束时都把日志认证为真实正确。' },
      vi: { inspector: 'Bạn đã xác nhận nhật ký bảy ngày qua chưa?', driver: 'Vâng, cuối mỗi ngày tôi đều xác nhận nhật ký là đúng và chính xác.' },
      es: { inspector: '¿Ha certificado sus registros de los últimos siete días?', driver: 'Sí, inspector, certifico los registros al final de cada día como verdaderos y correctos.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਪਿਛਲੇ ਸੱਤ ਦਿਨਾਂ ਦੇ ਲੋਗ ਪ੍ਰਮਾਣਿਤ ਕੀਤੇ ਹਨ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਹਰ ਦਿਨ ਖਤਮ ਹੋਣ ਤੇ ਲੋਗ ਨੂੰ ਸੱਚਾ ਤੇ ਸਹੀ ਪ੍ਰਮਾਣਿਤ ਕਰਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आपने पिछले सात दिनों के लॉग प्रमाणित कर दिए हैं?', driver: 'जी हाँ निरीक्षक, मैं हर दिन के अंत में लॉग को सच्चा और सही प्रमाणित करता हूँ।' },
    } },

  // ── Inspection Actions ───────────────────────────────────
  { category: 'inspection', en: 'Pre-trip Inspection', zh: '车前检查', vi: 'kiểm tra trước chuyến đi', es: 'inspección previa al viaje', pa: 'ਸਫਰ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚ', hi: 'यात्रा से पहले जांच',
    inspector: 'When did you complete your pre-trip inspection today?',
    driver: 'I did my pre-trip inspection at 5:45 a.m., inspector, before I started driving.',
    convTrans: {
      zh: { inspector: '你今天的车前检查是什么时候完成的？', driver: '今天早上 5:45 完成的，警官，然后才开始开车。' },
      vi: { inspector: 'Hôm nay bạn hoàn tất kiểm tra trước chuyến lúc nào?', driver: 'Tôi làm kiểm tra trước chuyến lúc 5:45 sáng, trước khi bắt đầu lái.' },
      es: { inspector: '¿Cuándo completó su inspección previa al viaje hoy?', driver: 'Hice la inspección previa a las 5:45 a. m., antes de empezar a conducir.' },
      pa: { inspector: 'ਅੱਜ ਤੁਸੀਂ ਪ੍ਰੀ-ਟ੍ਰਿਪ ਜਾਂਚ ਕਦੋਂ ਪੂਰੀ ਕੀਤੀ?', driver: 'ਮੈਂ ਸਵੇਰੇ 5:45 ਵਜੇ ਪ੍ਰੀ-ਟ੍ਰਿਪ ਜਾਂਚ ਕੀਤੀ, ਫਿਰ ਡ੍ਰਾਈਵਿੰਗ ਸ਼ੁਰੂ ਕੀਤੀ।' },
      hi: { inspector: 'आज आपने प्री-ट्रिप जांच कब पूरी की?', driver: 'मैंने सुबह 5:45 बजे प्री-ट्रिप जांच की, फिर ड्राइविंग शुरू की।' },
    } },
  { category: 'inspection', en: 'Post-trip Inspection', zh: '车后检查', vi: 'kiểm tra sau chuyến đi', es: 'inspección después del viaje', pa: 'ਸਫਰ ਤੋਂ ਬਾਅਦ ਜਾਂਚ', hi: 'यात्रा के बाद जांच',
    inspector: 'Did you perform a post-trip inspection when you parked last night?',
    driver: 'Yes, inspector, I did a full post-trip inspection and filled out my DVIR.',
    convTrans: {
      zh: { inspector: '昨晚你停车后做了车后检查吗？', driver: '做了，警官，我做了完整的车后检查并填写了 DVIR。' },
      vi: { inspector: 'Tối qua khi đỗ xe bạn có làm kiểm tra sau chuyến không?', driver: 'Vâng, tôi đã làm kiểm tra sau chuyến đầy đủ và điền DVIR.' },
      es: { inspector: '¿Hizo una inspección posterior al viaje cuando estacionó anoche?', driver: 'Sí, inspector, hice una inspección completa y llené el DVIR.' },
      pa: { inspector: 'ਰਾਤ ਪਾਰਕ ਕਰਨ ਮਗਰੋਂ ਕੀ ਤੁਸੀਂ ਪੋਸਟ-ਟ੍ਰਿਪ ਜਾਂਚ ਕੀਤੀ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਪੂਰੀ ਪੋਸਟ-ਟ੍ਰਿਪ ਜਾਂਚ ਕੀਤੀ ਤੇ DVIR ਭਰਿਆ।' },
      hi: { inspector: 'पिछली रात पार्क करने के बाद क्या आपने पोस्ट-ट्रिप जांच की?', driver: 'जी हाँ निरीक्षक, मैंने पूरी पोस्ट-ट्रिप जांच की और DVIR भर दिया।' },
    } },
  { category: 'inspection', en: 'DVIR (Driver Vehicle Inspection Report)', zh: '每日检查报告', vi: 'báo cáo kiểm tra xe hàng ngày', es: 'informe de inspección del vehículo (DVIR)', pa: 'ਡਰਾਈਵਰ ਵਾਹਨ ਜਾਂਚ ਰਿਪੋਰਟ', hi: 'वाहन निरीक्षण रिपोर्ट (DVIR)',
    inspector: 'Did you note this defect on your DVIR, the Driver Vehicle Inspection Report?',
    driver: 'Yes, inspector, I reported it on last night DVIR so maintenance can fix it.',
    convTrans: {
      zh: { inspector: '这个缺陷你有没有记在 DVIR 上？', driver: '记了，警官，我昨晚在 DVIR 上报告了，维修部门会处理。' },
      vi: { inspector: 'Lỗi này bạn có ghi vào DVIR (báo cáo kiểm tra) không?', driver: 'Vâng, tôi ghi vào DVIR tối qua để bảo trì sửa.' },
      es: { inspector: '¿Anotó este defecto en su DVIR, el informe de inspección del vehículo?', driver: 'Sí, inspector, lo reporté en el DVIR de anoche para que mantenimiento lo repare.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਇਹ ਖਰਾਬੀ ਆਪਣੇ DVIR ਉੱਤੇ ਨੋਟ ਕੀਤੀ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਰਾਤ ਨੂੰ DVIR ਉੱਤੇ ਰਿਪੋਰਟ ਕੀਤੀ ਤਾਂ ਜੋ ਮੈਂਟੀਨੈਂਸ ਠੀਕ ਕਰ ਸਕੇ।' },
      hi: { inspector: 'क्या आपने इस खराबी को अपने DVIR पर दर्ज किया?', driver: 'जी हाँ निरीक्षक, मैंने पिछली रात के DVIR में रिपोर्ट किया ताकि मेंटेनेंस ठीक कर सके।' },
    } },

  // ── Legal / Medical ──────────────────────────────────────
  { category: 'legal_medical', en: 'Medical Examiner Certificate', zh: '体检合格证', vi: 'giấy chứng nhận khám sức khỏe', es: 'certificado del examinador médico', pa: 'ਮੈਡਿਕਲ ਏਗਜ਼ੈਮਿਨਰ ਸਰਟੀਫਿਕੇਟ', hi: 'मेडिकल परीक्षक प्रमाणपत्र',
    inspector: 'Do you have your current Medical Examiner Certificate with you today?',
    driver: 'Yes, inspector, here is my Medical Examiner Certificate showing I am cleared to drive.',
    convTrans: {
      zh: { inspector: '你今天带着有效的体检合格证吗？', driver: '带了，警官，这是我的体检合格证，证明我可以驾驶。' },
      vi: { inspector: 'Hôm nay bạn có mang giấy chứng nhận khám sức khỏe hiện hành không?', driver: 'Vâng, đây là giấy chứng nhận cho thấy tôi đủ sức khỏe để lái.' },
      es: { inspector: '¿Tiene hoy su Certificado del Examinador Médico vigente?', driver: 'Sí, inspector, aquí está mi certificado que muestra que estoy apto para conducir.' },
      pa: { inspector: 'ਕੀ ਅੱਜ ਤੁਹਾਡੇ ਕੋਲ ਮੌਜੂਦਾ ਮੈਡਿਕਲ ਏਗਜ਼ੈਮਿਨਰ ਸਰਟੀਫਿਕੇਟ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਇਹ ਮੇਰਾ ਸਰਟੀਫਿਕੇਟ ਹੈ ਜੋ ਦੱਸਦਾ ਹੈ ਕਿ ਮੈਂ ਡ੍ਰਾਈਵ ਕਰਨ ਯੋਗ ਹਾਂ।' },
      hi: { inspector: 'क्या आज आपके पास वर्तमान मेडिकल परीक्षक प्रमाणपत्र है?', driver: 'जी हाँ निरीक्षक, यह मेरा प्रमाणपत्र है जो दिखाता है कि मैं चलाने योग्य हूँ।' },
    } },
  { category: 'legal_medical', en: 'Long Form Physical', zh: '体检详细表', vi: 'hồ sơ khám sức khỏe chi tiết', es: 'examen físico detallado (formulario largo)', pa: 'ਲਾਂਗ ਫੌਰਮ ਫਿਜ਼ੀਕਲ', hi: 'लंबा शारीरिक परीक्षण फॉर्म',
    inspector: 'Does your company keep a copy of your Long Form Physical on file?',
    driver: 'Yes, inspector, they have the Long Form Physical at the office and I carry the card.',
    convTrans: {
      zh: { inspector: '你们公司是否存有你的体检详细表副本？', driver: '有的，警官，详细表在公司办公室，我随身带着卡片。' },
      vi: { inspector: 'Công ty bạn có giữ bản sao hồ sơ khám sức khỏe chi tiết không?', driver: 'Vâng, công ty giữ bản chi tiết tại văn phòng, tôi mang thẻ.' },
      es: { inspector: '¿Su empresa guarda una copia de su examen físico detallado?', driver: 'Sí, inspector, la oficina tiene el formulario largo y yo llevo la tarjeta.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡੀ ਕੰਪਨੀ ਕੋਲ ਤੁਹਾਡੀ ਲਾਂਗ ਫੌਰਮ ਫਿਜ਼ੀਕਲ ਦੀ ਕਾਪੀ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਦਫਤਰ ਵਿੱਚ ਲਾਂਗ ਫੌਰਮ ਹੈ ਤੇ ਮੈਂ ਕਾਰਡ ਨਾਲ ਰੱਖਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आपकी कंपनी आपके लॉन्ग फॉर्म फिज़िकल की कॉपी रखती है?', driver: 'जी हाँ निरीक्षक, ऑफ़िस में लॉन्ग फॉर्म रखा है और मैं कार्ड साथ रखता हूँ।' },
    } },
  { category: 'legal_medical', en: 'Skill Performance Evaluation (SPE)', zh: '技能评估证书', vi: 'chứng nhận đánh giá kỹ năng', es: 'evaluación de desempeño de habilidades (SPE)', pa: 'ਸਕਿਲ ਪਰਫਾਰਮੈਂਸ ਇਵੈਲੂਏਸ਼ਨ ਸਰਟੀਫਿਕੇਟ', hi: 'कौशल प्रदर्शन मूल्यांकन प्रमाणपत्र',
    inspector: 'Are you driving under a Skill Performance Evaluation, or SPE, certificate?',
    driver: 'Yes, inspector, I have an SPE certificate because of my disability.',
    convTrans: {
      zh: { inspector: '你是凭技能评估证书（SPE）驾驶的吗？', driver: '是的，警官，由于我有残疾，所以持有 SPE 证书。' },
      vi: { inspector: 'Bạn có lái dưới chứng nhận đánh giá kỹ năng (SPE) không?', driver: 'Vâng, tôi có chứng nhận SPE vì khuyết tật.' },
      es: { inspector: '¿Está conduciendo bajo una Evaluación de Desempeño de Habilidades (SPE)?', driver: 'Sí, inspector, tengo un certificado SPE debido a mi discapacidad.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ SPE ਸਰਟੀਫਿਕੇਟ ਅਧੀਨ ਡ੍ਰਾਈਵ ਕਰ ਰਹੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰੇ ਕੋਲ ਅਪੰਗਤਾ ਕਾਰਨ SPE ਸਰਟੀਫਿਕੇਟ ਹੈ।' },
      hi: { inspector: 'क्या आप कौशल प्रदर्शन मूल्यांकन (SPE) के तहत चला रहे हैं?', driver: 'जी हाँ निरीक्षक, मेरी विकलांगता के कारण मेरे पास SPE प्रमाणपत्र है।' },
    } },
  { category: 'legal_medical', en: 'Medical Variance', zh: '医疗豁免', vi: 'miễn trừ y tế', es: 'excepción médica / variación médica', pa: 'ਮੈਡਿਕਲ ਛੂਟ', hi: 'चिकित्सीय छूट / वैरिएंस',
    inspector: 'Do you have a medical variance noted on your record?',
    driver: 'Yes, inspector, my medical variance is listed on my paperwork here.',
    convTrans: {
      zh: { inspector: '你的记录上有医疗豁免吗？', driver: '有的，警官，我的医疗豁免就写在这份文件上。' },
      vi: { inspector: 'Hồ sơ của bạn có ghi miễn trừ y tế không?', driver: 'Vâng, miễn trừ y tế của tôi có ghi trên giấy tờ này.' },
      es: { inspector: '¿Tiene una variación médica anotada en su expediente?', driver: 'Sí, inspector, mi variación médica figura aquí en mis documentos.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡੇ ਰਿਕਾਰਡ ਉੱਤੇ ਮੈਡਿਕਲ ਛੂਟ ਦਰਜ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰੀ ਮੈਡਿਕਲ ਛੂਟ ਇਸ ਕਾਗਜ਼ ਉੱਤੇ ਲਿਖੀ ਹੈ।' },
      hi: { inspector: 'क्या आपके रिकॉर्ड पर चिकित्सीय छूट दर्ज है?', driver: 'जी हाँ निरीक्षक, मेरी चिकित्सीय छूट इन कागज़ों पर दर्ज है।' },
    } },
  { category: 'legal_medical', en: 'Corrective Lenses', zh: '矫正镜片', vi: 'kính điều chỉnh / kính cận', es: 'lentes correctivos', pa: 'ਨਜ਼ਦੀਕ / ਦੂਰ ਦੀ ਐਨਕ', hi: 'सुधारक चश्मा',
    inspector: 'Does your license say you must wear corrective lenses when driving?',
    driver: 'Yes, inspector, my CDL requires corrective lenses and I am wearing my glasses.',
    convTrans: {
      zh: { inspector: '你的驾照是否注明驾驶时必须佩戴矫正镜片？', driver: '是的，警官，我的 CDL 要求戴矫正镜片，我现在戴着眼镜。' },
      vi: { inspector: 'Bằng lái của bạn có yêu cầu đeo kính khi lái không?', driver: 'Vâng, CDL của tôi yêu cầu đeo kính và tôi đang đeo.' },
      es: { inspector: '¿Su licencia indica que debe usar lentes correctivos al conducir?', driver: 'Sí, inspector, mi CDL exige lentes correctivos y llevo mis gafas.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡੇ ਲਾਇਸੈਂਸ ਉੱਤੇ ਡ੍ਰਾਈਵ ਕਰਦੇ ਸਮੇਂ ਐਨਕ ਪਾਉਣ ਦੀ ਸ਼ਰਤ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰਾ CDL ਐਨਕ ਮੰਗਦਾ ਹੈ ਤੇ ਮੈਂ ਪਾਈ ਹੋਈ ਹੈ।' },
      hi: { inspector: 'क्या आपके लाइसेंस पर ड्राइविंग के समय सुधारक चश्मा ज़रूरी है?', driver: 'जी हाँ निरीक्षक, मेरा CDL सुधारक चश्मा माँगता है और मैंने पहना हुआ है।' },
    } },
  { category: 'legal_medical', en: 'Hearing Aid', zh: '助听器', vi: 'máy trợ thính', es: 'aparato auditivo', pa: 'ਸੁਣਨ ਵਾਲਾ ਯੰਤਰ', hi: 'श्रवण यंत्र',
    inspector: 'Do you use a hearing aid while driving this commercial vehicle?',
    driver: 'Yes, inspector, I wear a hearing aid and it is working properly.',
    convTrans: {
      zh: { inspector: '驾驶这辆商用车时你戴助听器吗？', driver: '戴的，警官，我戴着助听器，工作正常。' },
      vi: { inspector: 'Khi lái xe thương mại, bạn có dùng máy trợ thính không?', driver: 'Vâng, tôi đeo máy trợ thính và nó hoạt động tốt.' },
      es: { inspector: '¿Usa aparato auditivo al conducir este vehículo comercial?', driver: 'Sí, inspector, uso aparato auditivo y funciona correctamente.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਇਸ ਵਪਾਰਕ ਵਾਹਨ ਨੂੰ ਚਲਾਉਂਦੇ ਸਮੇਂ ਸੁਣਨ ਵਾਲਾ ਯੰਤਰ ਵਰਤਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਸੁਣਨ ਵਾਲਾ ਯੰਤਰ ਪਾਇਆ ਹੈ ਤੇ ਇਹ ਸਹੀ ਚੱਲ ਰਿਹਾ ਹੈ।' },
      hi: { inspector: 'क्या आप इस वाणिज्यिक वाहन को चलाते समय श्रवण यंत्र इस्तेमाल करते हैं?', driver: 'जी हाँ निरीक्षक, मैंने श्रवण यंत्र पहना है और यह सही काम कर रहा है।' },
    } },
  { category: 'legal_medical', en: 'Medically Qualified', zh: '医学合格', vi: 'đủ điều kiện y tế', es: 'médicamente apto', pa: 'ਮੈਡੀਕਲੀ ਕਵਾਲੀਫਾਈਡ', hi: 'चिकित्सकीय रूप से योग्य',
    inspector: 'Are you currently medically qualified to operate a CMV?',
    driver: 'Yes, inspector, I am medically qualified and my card is still valid.',
    convTrans: {
      zh: { inspector: '你目前医学上是否合格驾驶 CMV？', driver: '合格，警官，我目前医学合格，卡片仍然有效。' },
      vi: { inspector: 'Hiện tại bạn có đủ điều kiện y tế để điều khiển CMV không?', driver: 'Vâng, tôi đủ điều kiện và thẻ vẫn còn hiệu lực.' },
      es: { inspector: '¿Está actualmente apto médicamente para operar un CMV?', driver: 'Sí, inspector, estoy médicamente apto y mi tarjeta sigue vigente.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਇਸ ਵੇਲੇ CMV ਚਲਾਉਣ ਲਈ ਮੈਡੀਕਲੀ ਕਵਾਲੀਫਾਈਡ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਕਵਾਲੀਫਾਈਡ ਹਾਂ ਤੇ ਮੇਰਾ ਕਾਰਡ ਅਜੇ ਚਲਦਾ ਹੈ।' },
      hi: { inspector: 'क्या आप वर्तमान में CMV चलाने के लिए चिकित्सकीय रूप से योग्य हैं?', driver: 'जी हाँ निरीक्षक, मैं योग्य हूँ और मेरा कार्ड अभी मान्य है।' },
    } },
  { category: 'legal_medical', en: 'License Endorsement', zh: '驾照背书', vi: 'chứng nhận bổ sung trên bằng lái', es: 'endoso en la licencia', pa: 'ਲਾਇਸੈਂਸ ਐਂਡੋਰਸਮੈਂਟ', hi: 'लाइसेंस अनुमोदन',
    inspector: 'What license endorsement do you have for this type of work?',
    driver: 'I have a tanker and hazmat license endorsement, inspector.',
    convTrans: {
      zh: { inspector: '你这类工作有什么驾照背书？', driver: '我有罐车和危险品的驾照背书，警官。' },
      vi: { inspector: 'Bạn có chứng nhận bổ sung gì trên bằng lái cho công việc này?', driver: 'Tôi có chứng nhận tanker và hazmat, thưa thanh tra.' },
      es: { inspector: '¿Qué endoso de licencia tiene para este tipo de trabajo?', driver: 'Tengo endosos de cisterna y hazmat, inspector.' },
      pa: { inspector: 'ਇਸ ਕੰਮ ਲਈ ਤੁਹਾਡੇ ਕੋਲ ਕਿਹੜਾ ਲਾਇਸੈਂਸ ਐਂਡੋਰਸਮੈਂਟ ਹੈ?', driver: 'ਸਾਹਬ, ਮੇਰੇ ਕੋਲ ਟੈਂਕਰ ਅਤੇ ਹੈਜ਼ਮੈਟ ਐਂਡੋਰਸਮੈਂਟ ਹੈ।' },
      hi: { inspector: 'इस तरह के काम के लिए आपके पास कौन-सा लाइसेंस अनुमोदन है?', driver: 'निरीक्षक, मेरे पास टैंकर और हैज़मैट अनुमोदन है।' },
    } },
  { category: 'legal_medical', en: 'Hazmat Endorsement', zh: '危险品背书', vi: 'chứng nhận chở hàng nguy hiểm', es: 'endoso de materiales peligrosos (hazmat)', pa: 'ਹੈਜ਼ਮੈਟ ਐਂਡੋਰਸਮੈਂਟ', hi: 'हैज़मैट अनुमोदन',
    inspector: 'Do you hold a current hazmat endorsement on your CDL?',
    driver: 'Yes, inspector, my hazmat endorsement is active and shown on the license.',
    convTrans: {
      zh: { inspector: '你的 CDL 上有当前有效的危险品背书吗？', driver: '有的，警官，危险品背书有效，已在驾照上显示。' },
      vi: { inspector: 'Bạn có chứng nhận hazmat hiệu lực trên CDL không?', driver: 'Vâng, chứng nhận hazmat đang hiệu lực và in trên bằng.' },
      es: { inspector: '¿Tiene un endoso hazmat vigente en su CDL?', driver: 'Sí, inspector, mi endoso hazmat está activo y aparece en la licencia.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡੇ CDL ਉੱਤੇ ਮੌਜੂਦਾ ਹੈਜ਼ਮੈਟ ਐਂਡੋਰਸਮੈਂਟ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਹੈਜ਼ਮੈਟ ਐਂਡੋਰਸਮੈਂਟ ਚਾਲੂ ਹੈ ਤੇ ਲਾਇਸੈਂਸ ਉੱਤੇ ਦਿਖਦਾ ਹੈ।' },
      hi: { inspector: 'क्या आपके CDL पर वर्तमान हैज़मैट अनुमोदन है?', driver: 'जी हाँ निरीक्षक, मेरा हैज़मैट अनुमोदन सक्रिय है और लाइसेंस पर दिखता है।' },
    } },
  { category: 'legal_medical', en: 'Doubles/Triples Endorsement', zh: '双/三挂背书', vi: 'chứng nhận moóc đôi / ba', es: 'endoso de dobles / triples', pa: 'ਡਬਲ / ਟ੍ਰਿਪਲ ਟ੍ਰੇਲਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'डबल/ट्रिपल अनुमोदन',
    inspector: 'Do you have a doubles/triples endorsement to pull multiple trailers?',
    driver: 'Yes, inspector, my CDL includes a doubles/triples endorsement.',
    convTrans: {
      zh: { inspector: '你有双挂/三挂背书来拖多个挂车吗？', driver: '有的，警官，我的 CDL 包含双挂/三挂背书。' },
      vi: { inspector: 'Bạn có chứng nhận moóc đôi/ba để kéo nhiều moóc không?', driver: 'Vâng, CDL của tôi có chứng nhận moóc đôi/ba.' },
      es: { inspector: '¿Tiene endoso de dobles/triples para llevar varios remolques?', driver: 'Sí, inspector, mi CDL incluye el endoso de dobles/triples.' },
      pa: { inspector: 'ਕਈ ਟ੍ਰੇਲਰ ਖਿੱਚਣ ਲਈ ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਡਬਲ/ਟ੍ਰਿਪਲ ਐਂਡੋਰਸਮੈਂਟ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰੇ CDL ਵਿੱਚ ਡਬਲ/ਟ੍ਰਿਪਲ ਐਂਡੋਰਸਮੈਂਟ ਹੈ।' },
      hi: { inspector: 'क्या आपके पास कई ट्रेलर खींचने के लिए डबल/ट्रिपल अनुमोदन है?', driver: 'जी हाँ निरीक्षक, मेरे CDL में डबल/ट्रिपल अनुमोदन शामिल है।' },
    } },
  { category: 'legal_medical', en: 'Tanker Endorsement', zh: '罐车背书', vi: 'chứng nhận xe bồn', es: 'endoso de cisterna (tanker)', pa: 'ਟੈਂਕਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'टैंकर अनुमोदन',
    inspector: 'Is a tanker endorsement required for the load you are hauling today?',
    driver: 'Yes, inspector, that is why I obtained the tanker endorsement last year.',
    convTrans: {
      zh: { inspector: '你今天拉的货是否需要罐车背书？', driver: '需要，警官，所以我去年取得了罐车背书。' },
      vi: { inspector: 'Hàng bạn chở hôm nay có cần chứng nhận xe bồn không?', driver: 'Vâng, vì vậy năm ngoái tôi đã lấy chứng nhận tanker.' },
      es: { inspector: '¿Se requiere endoso de cisterna para la carga que lleva hoy?', driver: 'Sí, inspector, por eso obtuve el endoso tanker el año pasado.' },
      pa: { inspector: 'ਅੱਜ ਜੋ ਲੋਡ ਤੁਸੀਂ ਲੈ ਕੇ ਜਾ ਰਹੇ ਹੋ, ਕੀ ਉਸ ਲਈ ਟੈਂਕਰ ਐਂਡੋਰਸਮੈਂਟ ਚਾਹੀਦਾ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਇਸੇ ਲਈ ਮੈਂ ਪਿਛਲੇ ਸਾਲ ਟੈਂਕਰ ਐਂਡੋਰਸਮੈਂਟ ਲਿਆ ਸੀ।' },
      hi: { inspector: 'क्या आज जो लोड ले जा रहे हैं, उसके लिए टैंकर अनुमोदन ज़रूरी है?', driver: 'जी हाँ निरीक्षक, इसीलिए मैंने पिछले साल टैंकर अनुमोदन लिया था।' },
    } },
  { category: 'legal_medical', en: 'Passenger Endorsement', zh: '客运背书', vi: 'chứng nhận chở khách', es: 'endoso de pasajeros', pa: 'ਪੈਸੇਂਜਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'यात्री अनुमोदन',
    inspector: 'Do you also have a passenger endorsement on your license?',
    driver: 'No, inspector, I do not have a passenger endorsement, only freight endorsements.',
    convTrans: {
      zh: { inspector: '你的驾照上也有客运背书吗？', driver: '没有，警官，我没有客运背书，只有货运的背书。' },
      vi: { inspector: 'Bằng lái của bạn có chứng nhận chở khách không?', driver: 'Không, tôi chỉ có chứng nhận chở hàng.' },
      es: { inspector: '¿Tiene también un endoso de pasajeros en su licencia?', driver: 'No, inspector, no tengo endoso de pasajeros, solo de carga.' },
      pa: { inspector: 'ਕੀ ਤੁਹਾਡੇ ਲਾਇਸੈਂਸ ਉੱਤੇ ਪੈਸੇਂਜਰ ਐਂਡੋਰਸਮੈਂਟ ਵੀ ਹੈ?', driver: 'ਨਹੀਂ ਸਾਹਬ, ਮੇਰੇ ਕੋਲ ਪੈਸੇਂਜਰ ਨਹੀਂ, ਸਿਰਫ ਮਾਲ ਢੋਣ ਦੇ ਐਂਡੋਰਸਮੈਂਟ ਹਨ।' },
      hi: { inspector: 'क्या आपके लाइसेंस पर यात्री अनुमोदन भी है?', driver: 'नहीं निरीक्षक, मेरे पास यात्री अनुमोदन नहीं है, केवल माल ढुलाई के अनुमोदन हैं।' },
    } },

  // ── Documents / Permits ──────────────────────────────────
  { category: 'documents', en: 'RODS (Record of Duty Status)', zh: '值勤状态记录', vi: 'sổ ghi trạng thái làm việc', es: 'registro de estado de servicio (RODS)', pa: 'ਡਿਊਟੀ ਸਟੇਟਸ ਰਿਕਾਰਡ', hi: 'ड्यूटी स्थिति रिकॉर्ड (RODS)',
    inspector: 'Your ELD keeps your RODS, or Record of Duty Status, correct?',
    driver: 'Yes, inspector, all my RODS are stored in the ELD system.',
    convTrans: {
      zh: { inspector: '你的 ELD 保存着你的 RODS（值勤状态记录），对吗？', driver: '对的，警官，我所有的 RODS 都存在 ELD 系统里。' },
      vi: { inspector: 'ELD của bạn lưu RODS, tức Record of Duty Status, đúng không?', driver: 'Vâng, toàn bộ RODS của tôi nằm trong hệ thống ELD.' },
      es: { inspector: 'Su ELD guarda su RODS, el registro de estado de servicio, ¿correcto?', driver: 'Sí, inspector, todos mis RODS están almacenados en el sistema ELD.' },
      pa: { inspector: 'ਤੁਹਾਡਾ ELD RODS (ਡਿਊਟੀ ਸਟੇਟਸ ਰਿਕਾਰਡ) ਰੱਖਦਾ ਹੈ, ਠੀਕ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰੇ ਸਾਰੇ RODS ELD ਸਿਸਟਮ ਵਿੱਚ ਹਨ।' },
      hi: { inspector: 'आपका ELD आपके RODS यानी ड्यूटी स्थिति रिकॉर्ड रखता है, सही?', driver: 'जी हाँ निरीक्षक, मेरे सभी RODS ELD सिस्टम में संग्रहीत हैं।' },
    } },
  { category: 'documents', en: 'Fuel Receipts', zh: '燃油收据', vi: 'hóa đơn nhiên liệu', es: 'recibos de combustible', pa: 'ਫਿਊਲ ਰਸੀਦਾਂ', hi: 'ईंधन रसीदें',
    inspector: 'Where do you keep your fuel receipts for each load?',
    driver: 'I keep my fuel receipts in this envelope, inspector, and turn them in every week.',
    convTrans: {
      zh: { inspector: '你每次运货的燃油收据放在哪里？', driver: '放在这个信封里，警官，每周交一次。' },
      vi: { inspector: 'Bạn để hóa đơn nhiên liệu cho mỗi chuyến ở đâu?', driver: 'Tôi để trong phong bì này và nộp hàng tuần.' },
      es: { inspector: '¿Dónde guarda los recibos de combustible de cada carga?', driver: 'Los guardo en este sobre, inspector, y los entrego cada semana.' },
      pa: { inspector: 'ਹਰ ਲੋਡ ਦੀ ਫਿਊਲ ਰਸੀਦ ਤੁਸੀਂ ਕਿੱਥੇ ਰੱਖਦੇ ਹੋ?', driver: 'ਸਾਹਬ, ਇਸ ਲਿਫ਼ਾਫ਼ੇ ਵਿੱਚ ਰੱਖਦਾ ਹਾਂ ਤੇ ਹਰ ਹਫ਼ਤੇ ਜਮ੍ਹਾਂ ਕਰਦਾ ਹਾਂ।' },
      hi: { inspector: 'हर लोड की ईंधन रसीदें कहाँ रखते हैं?', driver: 'इस लिफ़ाफ़े में रखता हूँ निरीक्षक, और हर हफ़्ते जमा करता हूँ।' },
    } },
  { category: 'documents', en: 'Toll Receipts', zh: '过路费收据', vi: 'hóa đơn phí cầu đường', es: 'recibos de peaje', pa: 'ਟੋਲ ਰਸੀਦਾਂ', hi: 'टोल रसीदें',
    inspector: 'Do you save your toll receipts for company records?',
    driver: 'Yes, inspector, I save all toll receipts and attach them to my trip report.',
    convTrans: {
      zh: { inspector: '你会为公司记录保留过路费收据吗？', driver: '会的，警官，我保留所有过路费收据并附在行程报告上。' },
      vi: { inspector: 'Bạn có giữ hóa đơn phí cầu đường cho công ty không?', driver: 'Vâng, tôi giữ tất cả hóa đơn và đính vào báo cáo chuyến.' },
      es: { inspector: '¿Guarda los recibos de peaje para los registros de la empresa?', driver: 'Sí, inspector, guardo todos los recibos y los adjunto al informe del viaje.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਕੰਪਨੀ ਲਈ ਟੋਲ ਰਸੀਦਾਂ ਸੰਭਾਲਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਸਾਰੀਆਂ ਰਸੀਦਾਂ ਰੱਖਦਾ ਹਾਂ ਤੇ ਟ੍ਰਿਪ ਰਿਪੋਰਟ ਨਾਲ ਲਾਉਂਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आप कंपनी रिकॉर्ड के लिए टोल रसीदें संभालते हैं?', driver: 'जी हाँ निरीक्षक, मैं सभी टोल रसीदें रखता हूँ और ट्रिप रिपोर्ट के साथ लगाता हूँ।' },
    } },
  { category: 'documents', en: 'Scale Tickets', zh: '过磅单', vi: 'phiếu cân xe', es: 'boletas de báscula', pa: 'ਵਜ਼ਨ ਪੱਤਰ / ਸਕੇਲ ਟਿਕਟ', hi: 'तौल पर्ची',
    inspector: 'Please show me your scale tickets for this shipment.',
    driver: 'Here are the scale tickets, inspector, from when I weighed at the truck stop.',
    convTrans: {
      zh: { inspector: '请给我看这批货的过磅单。', driver: '这是过磅单，警官，是我在卡车站过磅时拿到的。' },
      vi: { inspector: 'Vui lòng cho tôi xem phiếu cân xe cho chuyến này.', driver: 'Đây là phiếu cân, lấy khi tôi cân ở trạm dừng.' },
      es: { inspector: 'Muéstreme las boletas de báscula de este envío.', driver: 'Aquí están las boletas, inspector, de cuando pesé en el parador.' },
      pa: { inspector: 'ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਸ਼ਿਪਮੈਂਟ ਦੇ ਵਜ਼ਨ ਪੱਤਰ ਦਿਖਾਓ।', driver: 'ਇਹ ਸਕੇਲ ਟਿਕਟਾਂ ਹਨ ਸਾਹਬ, ਜੋ ਮੈਂ ਟਰੱਕ ਸਟਾਪ ਉੱਤੇ ਤੋਲ ਕੇ ਲਏ ਸਨ।' },
      hi: { inspector: 'इस शिपमेंट की तौल पर्चियाँ दिखाइए।', driver: 'ये रहीं तौल पर्चियाँ निरीक्षक, जो मैंने ट्रक स्टॉप पर तौल कराते समय ली थीं।' },
    } },
  { category: 'documents', en: 'Dispatch Records', zh: '调度记录', vi: 'hồ sơ điều phối', es: 'registros de despacho', pa: 'ਡਿਸਪੈਚ ਰਿਕਾਰਡ', hi: 'डिस्पैच रिकॉर्ड',
    inspector: 'Does dispatch keep detailed dispatch records for your loads?',
    driver: 'Yes, inspector, dispatch records every pickup and delivery in their system.',
    convTrans: {
      zh: { inspector: '调度方是否保留你每次运货的详细调度记录？', driver: '是的，警官，调度方在系统里记录每次提货和送货。' },
      vi: { inspector: 'Bộ phận điều phối có giữ hồ sơ chi tiết cho mỗi chuyến không?', driver: 'Vâng, điều phối ghi nhận mọi lần lấy và giao hàng trong hệ thống.' },
      es: { inspector: '¿Despacho lleva registros detallados de sus cargas?', driver: 'Sí, inspector, despacho registra cada recolección y entrega en su sistema.' },
      pa: { inspector: 'ਕੀ ਡਿਸਪੈਚ ਤੁਹਾਡੇ ਲੋਡਾਂ ਲਈ ਵਿਸਥਾਰ ਨਾਲ ਡਿਸਪੈਚ ਰਿਕਾਰਡ ਰੱਖਦਾ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਡਿਸਪੈਚ ਹਰ ਪਿਕਅੱਪ ਤੇ ਡਿਲਿਵਰੀ ਸਿਸਟਮ ਵਿੱਚ ਦਰਜ ਕਰਦਾ ਹੈ।' },
      hi: { inspector: 'क्या डिस्पैच आपके लोड के विस्तृत डिस्पैच रिकॉर्ड रखता है?', driver: 'जी हाँ निरीक्षक, डिस्पैच हर पिकअप और डिलिवरी अपने सिस्टम में दर्ज करता है।' },
    } },
  { category: 'documents', en: 'Trip Sheets', zh: '行程单', vi: 'bảng hành trình / phiếu chuyến đi', es: 'hojas de viaje', pa: 'ਟ੍ਰਿਪ ਸ਼ੀਟ', hi: 'ट्रिप शीट',
    inspector: 'Do you fill out trip sheets for each run?',
    driver: 'Yes, inspector, I complete trip sheets with miles and stops for every load.',
    convTrans: {
      zh: { inspector: '你每次跑车都填行程单吗？', driver: '是的，警官，每次运货我都填写里程和停靠点的行程单。' },
      vi: { inspector: 'Bạn có điền bảng hành trình cho mỗi chuyến không?', driver: 'Vâng, tôi điền số km và các điểm dừng cho mỗi chuyến.' },
      es: { inspector: '¿Llena hojas de viaje en cada recorrido?', driver: 'Sí, inspector, completo las hojas con millas y paradas para cada carga.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਹਰ ਚੱਕਰ ਲਈ ਟ੍ਰਿਪ ਸ਼ੀਟ ਭਰਦੇ ਹੋ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੈਂ ਹਰ ਲੋਡ ਲਈ ਮੀਲ ਤੇ ਸਟਾਪ ਨਾਲ ਟ੍ਰਿਪ ਸ਼ੀਟ ਪੂਰੀ ਕਰਦਾ ਹਾਂ।' },
      hi: { inspector: 'क्या आप हर रन के लिए ट्रिप शीट भरते हैं?', driver: 'जी हाँ निरीक्षक, मैं हर लोड के लिए माइल्स और स्टॉप के साथ ट्रिप शीट पूरी करता हूँ।' },
    } },
  { category: 'documents', en: 'GPS Data', zh: 'GPS数据', vi: 'dữ liệu GPS', es: 'datos de GPS', pa: 'GPS ਡਾਟਾ', hi: 'जीपीएस डेटा',
    inspector: 'Is your GPS data available if the company needs to check your route?',
    driver: 'Yes, inspector, my truck sends GPS data to our office in real time.',
    convTrans: {
      zh: { inspector: '如果公司需要核查你的路线，可以查到 GPS 数据吗？', driver: '可以，警官，我的卡车实时把 GPS 数据发送到公司办公室。' },
      vi: { inspector: 'Nếu công ty cần kiểm tra lộ trình, có lấy được dữ liệu GPS không?', driver: 'Vâng, xe của tôi gửi dữ liệu GPS về văn phòng theo thời gian thực.' },
      es: { inspector: '¿Están disponibles los datos de GPS si la empresa necesita revisar su ruta?', driver: 'Sí, inspector, mi camión envía datos de GPS a la oficina en tiempo real.' },
      pa: { inspector: 'ਜੇ ਕੰਪਨੀ ਤੁਹਾਡਾ ਰੂਟ ਚੈੱਕ ਕਰੇ, ਕੀ GPS ਡਾਟਾ ਮਿਲ ਜਾਵੇਗਾ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰਾ ਟਰੱਕ ਰੀਅਲ ਟਾਈਮ ਵਿੱਚ ਦਫਤਰ ਨੂੰ GPS ਡਾਟਾ ਭੇਜਦਾ ਹੈ।' },
      hi: { inspector: 'अगर कंपनी आपका रूट जांचना चाहे, क्या GPS डेटा उपलब्ध है?', driver: 'जी हाँ निरीक्षक, मेरा ट्रक रियल टाइम में हमारे ऑफ़िस को GPS डेटा भेजता है।' },
    } },
  { category: 'documents', en: 'Annual Inspection', zh: '年检报告', vi: 'báo cáo kiểm tra hàng năm', es: 'inspección anual', pa: 'ਸਾਲਾਨਾ ਜਾਂਚ ਰਿਪੋਰਟ', hi: 'वार्षिक निरीक्षण रिपोर्ट',
    inspector: 'Has this truck passed its required annual inspection?',
    driver: 'Yes, inspector, it passed the annual inspection last month.',
    convTrans: {
      zh: { inspector: '这辆卡车通过了必须的年检吗？', driver: '通过了，警官，上个月通过了年检。' },
      vi: { inspector: 'Chiếc xe này đã qua kiểm tra hàng năm chưa?', driver: 'Vâng, xe đã qua kiểm tra hàng năm tháng trước.' },
      es: { inspector: '¿Este camión pasó su inspección anual obligatoria?', driver: 'Sí, inspector, pasó la inspección anual el mes pasado.' },
      pa: { inspector: 'ਕੀ ਇਹ ਟਰੱਕ ਆਪਣੀ ਸਾਲਾਨਾ ਜਾਂਚ ਪਾਸ ਕਰ ਚੁੱਕਾ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਪਿਛਲੇ ਮਹੀਨੇ ਇਸਨੇ ਸਾਲਾਨਾ ਜਾਂਚ ਪਾਸ ਕੀਤੀ ਸੀ।' },
      hi: { inspector: 'क्या इस ट्रक ने अपनी ज़रूरी वार्षिक जांच पास की है?', driver: 'जी हाँ निरीक्षक, पिछले महीने इसने वार्षिक जांच पास की थी।' },
    } },
  { category: 'documents', en: 'Permit Book', zh: '证件夹', vi: 'sổ / bìa đựng giấy phép', es: 'libro de permisos', pa: 'ਪਰਮਿਟ ਬੁੱਕ', hi: 'परमिट बुक',
    inspector: 'Where do you keep your permit book in the cab?',
    driver: 'My permit book is in this compartment above the driver seat, inspector.',
    convTrans: {
      zh: { inspector: '你的证件夹放在驾驶室哪里？', driver: '在驾驶座上方的这个储物盒里，警官。' },
      vi: { inspector: 'Bạn để sổ giấy phép ở đâu trong cabin?', driver: 'Sổ giấy phép nằm trong ngăn phía trên ghế lái, thưa thanh tra.' },
      es: { inspector: '¿Dónde guarda su libro de permisos en la cabina?', driver: 'Mi libro de permisos está en este compartimento sobre el asiento del conductor.' },
      pa: { inspector: 'ਤੁਸੀਂ ਕੈਬ ਵਿੱਚ ਪਰਮਿਟ ਬੁੱਕ ਕਿੱਥੇ ਰੱਖਦੇ ਹੋ?', driver: 'ਡ੍ਰਾਈਵਰ ਦੀ ਸੀਟ ਉੱਪਰ ਇਸ ਖਾਨੇ ਵਿੱਚ ਹੈ, ਸਾਹਬ।' },
      hi: { inspector: 'आप केबिन में परमिट बुक कहाँ रखते हैं?', driver: 'मेरी परमिट बुक ड्राइवर सीट के ऊपर इस कम्पार्टमेंट में है, निरीक्षक।' },
    } },
  { category: 'documents', en: 'IFTA Permit', zh: 'IFTA许可', vi: 'giấy phép IFTA', es: 'permiso IFTA', pa: 'IFTA ਪਰਮਿਟ', hi: 'IFTA परमिट',
    inspector: 'Show me your IFTA permit, please.',
    driver: 'Yes, inspector, the IFTA permit is inside my permit book.',
    convTrans: {
      zh: { inspector: '请给我看你的 IFTA 许可。', driver: '好的，警官，IFTA 许可在我的证件夹里。' },
      vi: { inspector: 'Vui lòng cho tôi xem giấy phép IFTA.', driver: 'Vâng, giấy phép IFTA nằm trong sổ giấy phép của tôi.' },
      es: { inspector: 'Muéstreme su permiso IFTA, por favor.', driver: 'Sí, inspector, el permiso IFTA está dentro de mi libro de permisos.' },
      pa: { inspector: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ IFTA ਪਰਮਿਟ ਦਿਖਾਓ।', driver: 'ਹਾਂ ਸਾਹਬ, IFTA ਪਰਮਿਟ ਮੇਰੀ ਪਰਮਿਟ ਬੁੱਕ ਵਿੱਚ ਹੈ।' },
      hi: { inspector: 'कृपया अपना IFTA परमिट दिखाइए।', driver: 'जी हाँ निरीक्षक, IFTA परमिट मेरी परमिट बुक के अंदर है।' },
    } },
  { category: 'documents', en: 'IRP Registration', zh: 'IRP注册', vi: 'đăng ký IRP', es: 'registro IRP', pa: 'IRP ਰਜਿਸਟ੍ਰੇਸ਼ਨ', hi: 'IRP पंजीकरण',
    inspector: 'Do you have proof of your IRP registration in the truck?',
    driver: 'Yes, inspector, my IRP registration is printed on this cab card.',
    convTrans: {
      zh: { inspector: '车上有 IRP 注册的证明吗？', driver: '有的，警官，我的 IRP 注册印在这张车辆注册卡上。' },
      vi: { inspector: 'Bạn có bằng chứng đăng ký IRP trên xe không?', driver: 'Vâng, đăng ký IRP được in trên thẻ cab card này.' },
      es: { inspector: '¿Tiene prueba de su registro IRP en el camión?', driver: 'Sí, inspector, mi registro IRP está impreso en esta tarjeta de cabina.' },
      pa: { inspector: 'ਕੀ ਟਰੱਕ ਵਿੱਚ ਤੁਹਾਡੇ ਕੋਲ IRP ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਦਾ ਸਬੂਤ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਮੇਰਾ IRP ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਇਸ ਕੈਬ ਕਾਰਡ ਉੱਤੇ ਛਪਿਆ ਹੋਇਆ ਹੈ।' },
      hi: { inspector: 'क्या ट्रक में आपके IRP पंजीकरण का प्रमाण है?', driver: 'जी हाँ निरीक्षक, मेरा IRP पंजीकरण इस कैब कार्ड पर छपा है।' },
    } },
  { category: 'documents', en: 'Cab Card', zh: '车辆注册卡', vi: 'thẻ đăng ký xe (cab card)', es: 'tarjeta de cabina (cab card)', pa: 'ਕੈਬ ਕਾਰਡ', hi: 'कैब कार्ड',
    inspector: 'Is this the current cab card for this vehicle?',
    driver: 'Yes, inspector, this cab card matches the plate and VIN on the truck.',
    convTrans: {
      zh: { inspector: '这是这辆车当前的车辆注册卡吗？', driver: '是的，警官，这张卡与车牌和 VIN 匹配。' },
      vi: { inspector: 'Đây có phải là cab card hiện hành của xe này không?', driver: 'Vâng, cab card này khớp biển số và số VIN của xe.' },
      es: { inspector: '¿Es esta la tarjeta de cabina vigente para este vehículo?', driver: 'Sí, inspector, esta tarjeta coincide con la placa y el VIN del camión.' },
      pa: { inspector: 'ਕੀ ਇਹ ਇਸ ਵਾਹਨ ਦਾ ਮੌਜੂਦਾ ਕੈਬ ਕਾਰਡ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਇਹ ਕੈਬ ਕਾਰਡ ਟਰੱਕ ਦੇ ਪਲੇਟ ਤੇ VIN ਨਾਲ ਮਿਲਦਾ ਹੈ।' },
      hi: { inspector: 'क्या यह इस वाहन का वर्तमान कैब कार्ड है?', driver: 'जी हाँ निरीक्षक, यह कैब कार्ड ट्रक की प्लेट और VIN से मेल खाता है।' },
    } },
  { category: 'documents', en: 'Trailer Registration', zh: '挂车注册', vi: 'đăng ký rơ-moóc', es: 'registro del remolque', pa: 'ਟ੍ਰੇਲਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ', hi: 'ट्रेलर पंजीकरण',
    inspector: 'Can you show me the trailer registration for this unit?',
    driver: 'Here is the trailer registration, inspector, with the current year sticker.',
    convTrans: {
      zh: { inspector: '你能给我看这台挂车的注册吗？', driver: '这是挂车注册，警官，带本年度的贴纸。' },
      vi: { inspector: 'Bạn cho tôi xem đăng ký rơ-moóc của đơn vị này được không?', driver: 'Đây ạ, đăng ký rơ-moóc kèm tem năm hiện hành.' },
      es: { inspector: '¿Puede mostrarme el registro del remolque de esta unidad?', driver: 'Aquí está el registro del remolque, inspector, con la calcomanía del año en curso.' },
      pa: { inspector: 'ਕੀ ਤੁਸੀਂ ਇਸ ਯੂਨਿਟ ਦੀ ਟ੍ਰੇਲਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਦਿਖਾ ਸਕਦੇ ਹੋ?', driver: 'ਇਹ ਰਹੀ ਟ੍ਰੇਲਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਾਹਬ, ਮੌਜੂਦਾ ਸਾਲ ਦੇ ਸਟਿੱਕਰ ਨਾਲ।' },
      hi: { inspector: 'क्या आप इस यूनिट के ट्रेलर पंजीकरण को दिखा सकते हैं?', driver: 'ये रहा ट्रेलर पंजीकरण निरीक्षक, चालू वर्ष के स्टिकर के साथ।' },
    } },
  { category: 'documents', en: 'Insurance Certificate', zh: '保险证明', vi: 'giấy chứng nhận bảo hiểm', es: 'certificado de seguro', pa: 'ਬੀਮਾ ਸਰਟੀਫਿਕੇਟ', hi: 'बीमा प्रमाणपत्र',
    inspector: 'Do you have an insurance certificate for this vehicle?',
    driver: 'Yes, inspector, the insurance certificate is in my permit book.',
    convTrans: {
      zh: { inspector: '这辆车有保险证明吗？', driver: '有的，警官，保险证明在我的证件夹里。' },
      vi: { inspector: 'Bạn có giấy chứng nhận bảo hiểm cho xe này không?', driver: 'Vâng, giấy bảo hiểm nằm trong sổ giấy phép của tôi.' },
      es: { inspector: '¿Tiene un certificado de seguro para este vehículo?', driver: 'Sí, inspector, el certificado de seguro está en mi libro de permisos.' },
      pa: { inspector: 'ਕੀ ਇਸ ਵਾਹਨ ਲਈ ਤੁਹਾਡੇ ਕੋਲ ਬੀਮਾ ਸਰਟੀਫਿਕੇਟ ਹੈ?', driver: 'ਹਾਂ ਸਾਹਬ, ਬੀਮਾ ਸਰਟੀਫਿਕੇਟ ਮੇਰੀ ਪਰਮਿਟ ਬੁੱਕ ਵਿੱਚ ਹੈ।' },
      hi: { inspector: 'क्या इस वाहन के लिए आपके पास बीमा प्रमाणपत्र है?', driver: 'जी हाँ निरीक्षक, बीमा प्रमाणपत्र मेरी परमिट बुक में है।' },
    } },
  { category: 'documents', en: 'USDOT Number', zh: 'DOT编号', vi: 'số USDOT', es: 'número USDOT', pa: 'USDOT ਨੰਬਰ', hi: 'यूएसडीओटी नंबर',
    inspector: 'What is your company USDOT number?',
    driver: 'Our USDOT number is printed on the door and also here on the cab card, inspector.',
    convTrans: {
      zh: { inspector: '你们公司的 USDOT 编号是什么？', driver: '我们的 USDOT 编号印在车门上，也在这张车辆注册卡上，警官。' },
      vi: { inspector: 'Số USDOT của công ty bạn là bao nhiêu?', driver: 'Số USDOT in trên cửa xe và cũng có trên cab card này, thưa thanh tra.' },
      es: { inspector: '¿Cuál es el número USDOT de su empresa?', driver: 'Nuestro número USDOT está impreso en la puerta y también aquí en la tarjeta de cabina.' },
      pa: { inspector: 'ਤੁਹਾਡੀ ਕੰਪਨੀ ਦਾ USDOT ਨੰਬਰ ਕੀ ਹੈ?', driver: 'ਸਾਹਬ, ਸਾਡਾ USDOT ਨੰਬਰ ਦਰਵਾਜ਼ੇ ਉੱਤੇ ਤੇ ਇਸ ਕੈਬ ਕਾਰਡ ਉੱਤੇ ਵੀ ਛਪਿਆ ਹੈ।' },
      hi: { inspector: 'आपकी कंपनी का USDOT नंबर क्या है?', driver: 'निरीक्षक, हमारा USDOT नंबर दरवाज़े पर छपा है और इस कैब कार्ड पर भी है।' },
    } },
  { category: 'documents', en: 'MC Number', zh: '运营编号', vi: 'số MC', es: 'número MC (operador)', pa: 'MC ਨੰਬਰ', hi: 'एमसी नंबर',
    inspector: 'What is your MC number for operating authority?',
    driver: 'Inspector, our MC number is listed right here on this document.',
    convTrans: {
      zh: { inspector: '你们的运营授权 MC 编号是多少？', driver: '警官，我们的 MC 编号就写在这份文件上。' },
      vi: { inspector: 'Số MC cấp quyền hoạt động của bạn là bao nhiêu?', driver: 'Thưa thanh tra, số MC của chúng tôi ghi ngay trên tài liệu này.' },
      es: { inspector: '¿Cuál es su número MC de autoridad operativa?', driver: 'Inspector, nuestro número MC aparece aquí mismo en este documento.' },
      pa: { inspector: 'ਤੁਹਾਡੇ ਕੰਮ ਕਰਨ ਦੇ ਅਧਿਕਾਰ ਲਈ MC ਨੰਬਰ ਕੀ ਹੈ?', driver: 'ਸਾਹਬ, ਸਾਡਾ MC ਨੰਬਰ ਇਸ ਦਸਤਾਵੇਜ਼ ਉੱਤੇ ਦਰਜ ਹੈ।' },
      hi: { inspector: 'आपकी ऑपरेटिंग अथॉरिटी का MC नंबर क्या है?', driver: 'निरीक्षक, हमारा MC नंबर इस दस्तावेज़ पर यहाँ ही दर्ज है।' },
    } },
  { category: 'documents', en: 'Bill of Lading (BOL)', zh: '提单', vi: 'vận đơn', es: 'conocimiento de embarque (BOL)', pa: 'ਬਿਲ ਆਫ ਲੇਡਿੰਗ', hi: 'बिल ऑफ लेडिंग',
    inspector: 'Please hand me the Bill of Lading for this load.',
    driver: 'Yes, inspector, here is the Bill of Lading with the freight details.',
    convTrans: {
      zh: { inspector: '请把这批货的提单交给我。', driver: '好的，警官，这是提单，附有货物详情。' },
      vi: { inspector: 'Vui lòng đưa tôi vận đơn của chuyến này.', driver: 'Vâng, đây là vận đơn kèm thông tin lô hàng.' },
      es: { inspector: 'Por favor, entrégueme el Conocimiento de Embarque de esta carga.', driver: 'Sí, inspector, aquí está el BOL con los detalles de la mercancía.' },
      pa: { inspector: 'ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਲੋਡ ਦਾ ਬਿਲ ਆਫ ਲੇਡਿੰਗ ਦਿਓ।', driver: 'ਹਾਂ ਸਾਹਬ, ਇਹ ਬਿਲ ਆਫ ਲੇਡਿੰਗ ਹੈ, ਮਾਲ ਦੀਆਂ ਵਿਸਥਾਰ ਜਾਣਕਾਰੀ ਨਾਲ।' },
      hi: { inspector: 'कृपया इस लोड का बिल ऑफ लेडिंग दीजिए।', driver: 'जी हाँ निरीक्षक, ये रहा बिल ऑफ लेडिंग, माल के विवरण के साथ।' },
    } },
  { category: 'documents', en: 'Hazmat Shipping Papers', zh: '危险品运输文件', vi: 'giấy tờ vận chuyển hàng nguy hiểm', es: 'documentos de envío de materiales peligrosos', pa: 'ਖਤਰਨਾਕ ਸਮਾਨ ਦੀਆਂ ਡਾਕੂਮੈਂਟਸ', hi: 'खतरनाक माल शिपिंग कागजात',
    inspector: 'Are you carrying any hazmat shipping papers today?',
    driver: 'No, inspector, I have no hazmat shipping papers because this load is not hazardous.',
    convTrans: {
      zh: { inspector: '你今天有携带危险品运输文件吗？', driver: '没有，警官，这批货不是危险品，所以没有危险品运输文件。' },
      vi: { inspector: 'Hôm nay bạn có mang giấy tờ vận chuyển hàng nguy hiểm không?', driver: 'Không, hàng này không phải hàng nguy hiểm nên tôi không có giấy tờ hazmat.' },
      es: { inspector: '¿Lleva hoy documentos de envío de materiales peligrosos?', driver: 'No, inspector, no tengo documentos hazmat porque esta carga no es peligrosa.' },
      pa: { inspector: 'ਅੱਜ ਕੀ ਤੁਸੀਂ ਖਤਰਨਾਕ ਸਮਾਨ ਦੇ ਕਾਗਜ਼ ਲੈ ਕੇ ਜਾ ਰਹੇ ਹੋ?', driver: 'ਨਹੀਂ ਸਾਹਬ, ਇਹ ਲੋਡ ਖਤਰਨਾਕ ਨਹੀਂ ਹੈ, ਇਸ ਲਈ ਹੈਜ਼ਮੈਟ ਕਾਗਜ਼ ਨਹੀਂ ਹਨ।' },
      hi: { inspector: 'क्या आज आप कोई हैज़मैट शिपिंग कागज़ात साथ ले जा रहे हैं?', driver: 'नहीं निरीक्षक, यह लोड खतरनाक नहीं है, इसलिए हैज़मैट कागज़ात नहीं हैं।' },
    } },
  { category: 'documents', en: 'Weight Ticket', zh: '重量单', vi: 'phiếu cân nặng', es: 'ticket de peso', pa: 'ਵਜ਼ਨ ਟਿਕਟ', hi: 'वजन टिकट',
    inspector: 'Can I see your latest weight ticket for this cargo?',
    driver: 'Here is the weight ticket from the scale I used this morning, inspector.',
    convTrans: {
      zh: { inspector: '我可以看一下这批货最新的重量单吗？', driver: '这是我今天早上过磅时拿到的重量单，警官。' },
      vi: { inspector: 'Cho tôi xem phiếu cân mới nhất cho hàng này được không?', driver: 'Đây là phiếu cân tôi lấy ở trạm cân sáng nay, thưa thanh tra.' },
      es: { inspector: '¿Puedo ver su ticket de peso más reciente para esta carga?', driver: 'Aquí está el ticket de peso de la báscula que usé esta mañana, inspector.' },
      pa: { inspector: 'ਕੀ ਮੈਂ ਇਸ ਮਾਲ ਦਾ ਤਾਜ਼ਾ ਵਜ਼ਨ ਟਿਕਟ ਵੇਖ ਸਕਦਾ ਹਾਂ?', driver: 'ਇਹ ਉਹ ਵਜ਼ਨ ਟਿਕਟ ਹੈ ਸਾਹਬ, ਜੋ ਮੈਂ ਸਵੇਰੇ ਸਕੇਲ ਉੱਤੇ ਲਈ ਸੀ।' },
      hi: { inspector: 'क्या मैं इस माल का नवीनतम वजन टिकट देख सकता हूँ?', driver: 'ये रहा वजन टिकट जो मैंने आज सुबह तौल पर लिया था, निरीक्षक।' },
    } },
]
