// Trucking terminology — 6-language translations + inspector/driver conversation
// Source: terms.md (translations) + termsConvers.md (conversations).

export const TERM_CATEGORIES = [
  { id: 'core_eld',     icon: '📱', name_en: 'Core ELD / HOS',          name_zh: '核心 ELD/HOS',  name_es: 'ELD / HOS básico',      name_hi: 'मुख्य ELD/HOS',   name_pa: 'ਮੁੱਖ ELD/HOS',     name_vi: 'ELD/HOS cốt lõi' },
  { id: 'hos',          icon: '⏱',  name_en: 'HOS Concepts',            name_zh: 'HOS 概念',       name_es: 'Conceptos HOS',         name_hi: 'HOS अवधारणाएं',  name_pa: 'HOS ਧਾਰਨਾਵਾਂ',     name_vi: 'Khái niệm HOS' },
  { id: 'duty_status',  icon: '🅿️', name_en: 'PC / Yard Move',          name_zh: 'PC / 场内移动',  name_es: 'PC / Yard Move',        name_hi: 'PC / यार्ड मूव',  name_pa: 'PC / ਯਾਰਡ ਮੂਵ',   name_vi: 'PC / Yard Move' },
  { id: 'inspection',   icon: '🔍', name_en: 'Inspection Actions',      name_zh: '检查动作',       name_es: 'Acciones de inspección', name_hi: 'निरीक्षण क्रियाएं', name_pa: 'ਜਾਂਚ ਕਿਰਿਆਵਾਂ',  name_vi: 'Hành động kiểm tra' },
  { id: 'legal_medical',icon: '⚕️', name_en: 'Legal / Medical',         name_zh: '法律/医疗',     name_es: 'Legal / Médico',        name_hi: 'कानूनी/चिकित्सीय', name_pa: 'ਕਾਨੂੰਨੀ/ਮੈਡੀਕਲ',   name_vi: 'Pháp lý / Y tế' },
  { id: 'documents',    icon: '📋', name_en: 'Documents / Permits',     name_zh: '文件/许可',     name_es: 'Documentos / Permisos', name_hi: 'दस्तावेज़/परमिट',  name_pa: 'ਦਸਤਾਵੇਜ਼/ਪਰਮਿਟ', name_vi: 'Tài liệu / Giấy phép' },
]

export const TERMS = [
  // ── Core ELD / HOS ───────────────────────────────────────
  { category: 'core_eld', en: 'ELD (Electronic Logging Device)', zh: '电子行车日志设备', vi: 'thiết bị ghi dữ liệu điện tử (ELD)', es: 'dispositivo de registro electrónico (ELD)', pa: 'ਇਲੈਕਟ੍ਰਾਨਿਕ ਲੋਗਿੰਗ ਡਿਵਾਈਸ (ELD)', hi: 'इलेक्ट्रॉनिक लॉगिंग डिवाइस (ELD)',
    inspector: 'Please show me your ELD so I can review your last 8 days of logs.',
    driver: 'Yes, inspector, here is my electronic logging device screen with my log history.' },
  { category: 'core_eld', en: 'Paper Log', zh: '纸质日志', vi: 'sổ nhật ký giấy', es: 'registro en papel', pa: 'ਕਾਗਜ਼ੀ ਲੋਗ', hi: 'पेपर लॉग / कागज़ी रिकॉर्ड',
    inspector: 'Why are you using a paper log instead of your ELD today?',
    driver: 'The ELD failed this morning, so I switched to a paper log to stay compliant.' },
  { category: 'core_eld', en: 'Time Card', zh: '打卡记录', vi: 'thẻ chấm công', es: 'tarjeta de tiempo', pa: 'ਟਾਈਮ ਕਾਰਡ', hi: 'टाइम कार्ड',
    inspector: 'Do you normally record your local work on a time card?',
    driver: 'Yes, inspector, for local runs my company keeps a time card instead of a full logbook.' },
  { category: 'core_eld', en: 'Graph Grid (log grid)', zh: '日志图表', vi: 'lưới đồ thị nhật ký', es: 'cuadrícula del gráfico de registro', pa: 'ਲਾਗ ਗ੍ਰਾਫ ਗਰਿੱਡ', hi: 'ग्राफ ग्रिड (लॉग चार्ट)',
    inspector: 'On your old logs, did you fill out the graph grid correctly each day?',
    driver: 'Yes, inspector, I drew my duty status on the graph grid for every 24-hour period.' },
  { category: 'core_eld', en: 'Log Entry', zh: '日志条目', vi: 'mục ghi nhật ký', es: 'entrada de registro', pa: 'ਲੋਗ ਐਂਟਰੀ', hi: 'लॉग प्रविष्टि',
    inspector: 'When did you make the last log entry in your system?',
    driver: 'I created my last log entry when I went from off duty to driving at 7 a.m.' },
  { category: 'core_eld', en: 'Transfer Data', zh: '传输数据', vi: 'chuyển dữ liệu', es: 'transferir datos', pa: 'ਡਾਟਾ ਟ੍ਰਾਂਸਫਰ ਕਰਨਾ', hi: 'डेटा स्थानांतरण',
    inspector: 'Can you transfer data from your ELD to my system now?',
    driver: 'Yes, inspector, I will use the transfer data option on the ELD menu.' },
  { category: 'core_eld', en: 'Web Service (data transfer)', zh: '网络服务传输', vi: 'dịch vụ web (truyền dữ liệu)', es: 'servicio web (transferencia de datos)', pa: 'ਵੈੱਬ ਸੇਵਾ ਰਾਹੀਂ ਡਾਟਾ ਭੇਜਣਾ', hi: 'वेब सेवा द्वारा डेटा ट्रांसफर',
    inspector: 'Is your ELD set up to send logs by web service?',
    driver: 'Yes, inspector, I can send my records directly to enforcement using web service.' },
  { category: 'core_eld', en: 'Email Transfer', zh: '邮件传输', vi: 'gửi dữ liệu qua email', es: 'envío por correo electrónico', pa: 'ਈਮੇਲ ਰਾਹੀਂ ਭੇਜਣਾ', hi: 'ईमेल द्वारा ट्रांसफर',
    inspector: 'If web service fails, can you do an email transfer of your logs?',
    driver: 'Yes, inspector, I can send an email transfer to the official address from my ELD.' },
  { category: 'core_eld', en: 'Malfunction', zh: '故障', vi: 'trục trặc / hỏng hóc', es: 'malfunción', pa: 'ਖਰਾਬੀ', hi: 'खराबी / खराब होना',
    inspector: 'You reported an ELD malfunction yesterday; is it fixed now?',
    driver: 'Yes, inspector, the malfunction was repaired and the unit is working correctly today.' },
  { category: 'core_eld', en: 'Backup Paper Logs', zh: '备用纸质日志', vi: 'sổ nhật ký giấy dự phòng', es: 'registros en papel de respaldo', pa: 'ਬੈਕਅੱਪ ਕਾਗਜ਼ੀ ਲੋਗ', hi: 'बैकअप पेपर लॉग',
    inspector: 'Show me your backup paper logs in case the ELD stops working again.',
    driver: 'Here they are, inspector; I keep several backup paper logs in my permit book.' },
  { category: 'core_eld', en: '8 Days of Paper Logs', zh: '8天纸质日志记录', vi: '8 ngày nhật ký giấy', es: '8 días de registros en papel', pa: '8 ਦਿਨਾਂ ਦੇ ਕਾਗਜ਼ੀ ਲੋਗ', hi: '8 दिनों के पेपर लॉग',
    inspector: 'Regulations require at least 8 days of paper logs in the truck; do you have them?',
    driver: 'Yes, inspector, I have more than 8 days of blank paper logs ready to use.' },
  { category: 'core_eld', en: 'ELD Instruction Manual', zh: 'ELD操作手册', vi: 'sổ hướng dẫn ELD', es: 'manual de instrucciones del ELD', pa: 'ELD ਹਦਾਇਤ ਮੈਨੂਅਲ', hi: 'ELD निर्देश पुस्तिका',
    inspector: 'Where do you keep the ELD instruction manual in this cab?',
    driver: 'The ELD instruction manual is in this side pocket, inspector.' },

  // ── HOS Concepts ─────────────────────────────────────────
  { category: 'hos', en: 'HOS (Hours of Service)', zh: '工作时间规定', vi: 'quy định giờ làm việc / giờ lái xe', es: 'horas de servicio (HOS)', pa: 'ਡਿਊਟੀ ਘੰਟੇ / Hours of Service', hi: 'सेवा के घंटे (HOS)',
    inspector: 'Are you familiar with the basic HOS, or Hours of Service, rules?',
    driver: 'Yes, inspector, I follow the Hours of Service limits every day.' },
  { category: 'hos', en: '11-Hour Driving Limit', zh: '11小时驾驶上限', vi: 'giới hạn lái 11 giờ', es: 'límite de conducción de 11 horas', pa: '11 ਘੰਟੇ ਡ੍ਰਾਈਵਿੰਗ ਸੀਮਾ', hi: '11 घंटे ड्राइविंग सीमा',
    inspector: 'How many hours have you driven today under the 11-hour driving limit?',
    driver: 'I have driven 6 hours so far, inspector, so I am under the 11-hour driving limit.' },
  { category: 'hos', en: '14-Hour Window', zh: '14小时工作窗口', vi: 'khung 14 giờ làm việc', es: 'ventana de 14 horas', pa: '14 ਘੰਟਿਆਂ ਦੀ ਡਿਊਟੀ ਵਿੰਡੋ', hi: '14 घंटे की कार्य अवधि',
    inspector: 'What time did your 14-hour window start this morning?',
    driver: 'It started at 5 a.m., inspector, so my 14-hour window ends at 7 p.m.' },
  { category: 'hos', en: '30-Minute Break', zh: '30分钟休息', vi: 'nghỉ 30 phút', es: 'pausa de 30 minutos', pa: '30 ਮਿੰਟ ਵਿਸ਼ਰਾਮ', hi: '30 मिनट का ब्रेक',
    inspector: 'When did you take your required 30-minute break today?',
    driver: 'I took a 30-minute break at noon, inspector, after about 6 hours of driving.' },
  { category: 'hos', en: '70-Hour / 8-Day Cycle', zh: '70小时/8天周期', vi: 'chu kỳ 70 giờ / 8 ngày', es: 'ciclo de 70 horas / 8 días', pa: '70 ਘੰਟੇ / 8 ਦਿਨ ਚੱਕਰ', hi: '70 घंटे / 8 दिन चक्र',
    inspector: 'How many hours are left on your 70-hour/8-day cycle?',
    driver: 'I have 10 hours left in my 70-hour/8-day cycle, inspector.' },
  { category: 'hos', en: 'On Duty', zh: '值勤状态', vi: 'đang làm việc (on duty)', es: 'en servicio', pa: 'ਡਿਊਟੀ ਤੇ', hi: 'ड्यूटी पर (ऑन ड्यूटी)',
    inspector: 'At what time did you first go on duty this morning?',
    driver: 'I went on duty at 6 a.m., inspector, when I started my pre-trip inspection.' },
  { category: 'hos', en: 'Off Duty', zh: '休息状态', vi: 'nghỉ (off duty)', es: 'fuera de servicio / fuera de turno', pa: 'ਆਫ ਡਿਊਟੀ / ਛੁੱਟੀ', hi: 'ड्यूटी से बाहर (ऑफ ड्यूटी)',
    inspector: 'How many hours were you off duty last night?',
    driver: 'I was off duty for 10 full hours, inspector, before I started work today.' },
  { category: 'hos', en: 'Sleeper Berth', zh: '卧铺状态', vi: 'giường nằm / chế độ cabin ngủ', es: 'litera (sleeper berth)', pa: 'ਸਲੀਪਰ ਬਰਥ', hi: 'स्लीपर बर्थ',
    inspector: 'Did you spend part of your break in the sleeper berth?',
    driver: 'Yes, inspector, I slept 8 hours in the sleeper berth last night.' },
  { category: 'hos', en: 'Driving Status', zh: '驾驶状态', vi: 'trạng thái đang lái', es: 'estado de conducción', pa: 'ਡ੍ਰਾਈਵਿੰਗ ਸਟੇਟਸ', hi: 'ड्राइविंग स्थिति',
    inspector: 'Your ELD shows you in driving status for this period; is that correct?',
    driver: 'Yes, inspector, I was moving the truck the whole time, so driving status is correct.' },
  { category: 'hos', en: 'Remaining Hours', zh: '剩余小时', vi: 'giờ còn lại', es: 'horas restantes', pa: 'ਬਾਕੀ ਘੰਟੇ', hi: 'बचे हुए घंटे',
    inspector: 'How many remaining hours of drive time do you have today?',
    driver: 'My ELD shows I have 3 remaining hours of driving, inspector.' },
  { category: 'hos', en: 'Violation', zh: '违规', vi: 'vi phạm', es: 'infracción', pa: 'ਉਲੰਘਣਾ', hi: 'उल्लंघन',
    inspector: 'Do you see this HOS violation on your log from two days ago?',
    driver: 'Yes, inspector, I understand there is a violation and I will be more careful.' },
  { category: 'hos', en: 'Out of Service (OOS)', zh: '停运', vi: 'ngừng hoạt động / bị cấm chạy', es: 'fuera de servicio (OOS)', pa: 'ਆਉਟ ਆਫ ਸਰਵਿਸ', hi: 'सेवा से बाहर (OOS)',
    inspector: 'Because of this serious issue, I must place you out of service.',
    driver: 'I understand, inspector; while I am out of service I will not move the truck.' },

  // ── Special Duty Statuses ────────────────────────────────
  { category: 'duty_status', en: 'Personal Conveyance (PC)', zh: '私用驾驶模式', vi: 'chế độ di chuyển cá nhân (PC)', es: 'uso personal del vehículo (PC)', pa: 'ਪਰਸਨਲ ਕਨਵੇਅੰਸ ਮੋਡ', hi: 'पर्सनल कन्‍वेयंस (PC)',
    inspector: 'Did you use Personal Conveyance to drive from the receiver to this truck stop?',
    driver: 'Yes, inspector, I was empty and off duty, so I used Personal Conveyance.' },
  { category: 'duty_status', en: 'Yard Move (YM)', zh: '场内移动模式', vi: 'di chuyển trong bãi (YM)', es: 'movimiento en patio (YM)', pa: 'ਯਾਰਡ ਮੂਵ ਮੋਡ', hi: 'यार्ड मूव (YM)',
    inspector: 'Why is this move marked as Yard Move on your log?',
    driver: 'Inspector, I used Yard Move because I was just repositioning the truck inside the yard.' },
  { category: 'duty_status', en: 'Unassigned Driving Time', zh: '未分配驾驶时间', vi: 'thời gian lái xe chưa gán', es: 'tiempo de conducción no asignado', pa: 'ਅਣ-ਸੌਂਪਿਆ ਡ੍ਰਾਈਵਿੰਗ ਸਮਾਂ', hi: 'असाइन न किया गया ड्राइविंग समय',
    inspector: 'There is unassigned driving time on this truck; can you explain it?',
    driver: 'Yes, inspector, I forgot to log in that morning, so the driving shows as unassigned driving time.' },
  { category: 'duty_status', en: 'Edit Log', zh: '编辑日志', vi: 'chỉnh sửa nhật ký', es: 'editar el registro', pa: 'ਲੋਗ ਸੋਧਣਾ', hi: 'लॉग संपादित करना',
    inspector: 'Did you edit your log when you realized the status was wrong?',
    driver: 'Yes, inspector, I used the edit log function and added a note about the mistake.' },
  { category: 'duty_status', en: 'Certify Logs', zh: '认证日志', vi: 'xác nhận nhật ký', es: 'certificar los registros', pa: 'ਲੋਗ ਪ੍ਰਮਾਣਿਤ ਕਰਨਾ', hi: 'लॉग प्रमाणित करना',
    inspector: 'Have you certified your logs for the last seven days?',
    driver: 'Yes, inspector, I certify logs at the end of each day as true and correct.' },

  // ── Inspection Actions ───────────────────────────────────
  { category: 'inspection', en: 'Pre-trip Inspection', zh: '车前检查', vi: 'kiểm tra trước chuyến đi', es: 'inspección previa al viaje', pa: 'ਸਫਰ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚ', hi: 'यात्रा से पहले जांच',
    inspector: 'When did you complete your pre-trip inspection today?',
    driver: 'I did my pre-trip inspection at 5:45 a.m., inspector, before I started driving.' },
  { category: 'inspection', en: 'Post-trip Inspection', zh: '车后检查', vi: 'kiểm tra sau chuyến đi', es: 'inspección después del viaje', pa: 'ਸਫਰ ਤੋਂ ਬਾਅਦ ਜਾਂਚ', hi: 'यात्रा के बाद जांच',
    inspector: 'Did you perform a post-trip inspection when you parked last night?',
    driver: 'Yes, inspector, I did a full post-trip inspection and filled out my DVIR.' },
  { category: 'inspection', en: 'DVIR (Driver Vehicle Inspection Report)', zh: '每日检查报告', vi: 'báo cáo kiểm tra xe hàng ngày', es: 'informe de inspección del vehículo (DVIR)', pa: 'ਡਰਾਈਵਰ ਵਾਹਨ ਜਾਂਚ ਰਿਪੋਰਟ', hi: 'वाहन निरीक्षण रिपोर्ट (DVIR)',
    inspector: 'Did you note this defect on your DVIR, the Driver Vehicle Inspection Report?',
    driver: 'Yes, inspector, I reported it on last night DVIR so maintenance can fix it.' },

  // ── Legal / Medical ──────────────────────────────────────
  { category: 'legal_medical', en: 'Medical Examiner Certificate', zh: '体检合格证', vi: 'giấy chứng nhận khám sức khỏe', es: 'certificado del examinador médico', pa: 'ਮੈਡਿਕਲ ਏਗਜ਼ੈਮਿਨਰ ਸਰਟੀਫਿਕੇਟ', hi: 'मेडिकल परीक्षक प्रमाणपत्र',
    inspector: 'Do you have your current Medical Examiner Certificate with you today?',
    driver: 'Yes, inspector, here is my Medical Examiner Certificate showing I am cleared to drive.' },
  { category: 'legal_medical', en: 'Long Form Physical', zh: '体检详细表', vi: 'hồ sơ khám sức khỏe chi tiết', es: 'examen físico detallado (formulario largo)', pa: 'ਲਾਂਗ ਫੌਰਮ ਫਿਜ਼ੀਕਲ', hi: 'लंबा शारीरिक परीक्षण फॉर्म',
    inspector: 'Does your company keep a copy of your Long Form Physical on file?',
    driver: 'Yes, inspector, they have the Long Form Physical at the office and I carry the card.' },
  { category: 'legal_medical', en: 'Skill Performance Evaluation (SPE)', zh: '技能评估证书', vi: 'chứng nhận đánh giá kỹ năng', es: 'evaluación de desempeño de habilidades (SPE)', pa: 'ਸਕਿਲ ਪਰਫਾਰਮੈਂਸ ਇਵੈਲੂਏਸ਼ਨ ਸਰਟੀਫਿਕੇਟ', hi: 'कौशल प्रदर्शन मूल्यांकन प्रमाणपत्र',
    inspector: 'Are you driving under a Skill Performance Evaluation, or SPE, certificate?',
    driver: 'Yes, inspector, I have an SPE certificate because of my disability.' },
  { category: 'legal_medical', en: 'Medical Variance', zh: '医疗豁免', vi: 'miễn trừ y tế', es: 'excepción médica / variación médica', pa: 'ਮੈਡਿਕਲ ਛੂਟ', hi: 'चिकित्सीय छूट / वैरिएंस',
    inspector: 'Do you have a medical variance noted on your record?',
    driver: 'Yes, inspector, my medical variance is listed on my paperwork here.' },
  { category: 'legal_medical', en: 'Corrective Lenses', zh: '矫正镜片', vi: 'kính điều chỉnh / kính cận', es: 'lentes correctivos', pa: 'ਨਜ਼ਦੀਕ / ਦੂਰ ਦੀ ਐਨਕ', hi: 'सुधारक चश्मा',
    inspector: 'Does your license say you must wear corrective lenses when driving?',
    driver: 'Yes, inspector, my CDL requires corrective lenses and I am wearing my glasses.' },
  { category: 'legal_medical', en: 'Hearing Aid', zh: '助听器', vi: 'máy trợ thính', es: 'aparato auditivo', pa: 'ਸੁਣਨ ਵਾਲਾ ਯੰਤਰ', hi: 'श्रवण यंत्र',
    inspector: 'Do you use a hearing aid while driving this commercial vehicle?',
    driver: 'Yes, inspector, I wear a hearing aid and it is working properly.' },
  { category: 'legal_medical', en: 'Medically Qualified', zh: '医学合格', vi: 'đủ điều kiện y tế', es: 'médicamente apto', pa: 'ਮੈਡੀਕਲੀ ਕਵਾਲੀਫਾਈਡ', hi: 'चिकित्सकीय रूप से योग्य',
    inspector: 'Are you currently medically qualified to operate a CMV?',
    driver: 'Yes, inspector, I am medically qualified and my card is still valid.' },
  { category: 'legal_medical', en: 'License Endorsement', zh: '驾照背书', vi: 'chứng nhận bổ sung trên bằng lái', es: 'endoso en la licencia', pa: 'ਲਾਇਸੈਂਸ ਐਂਡੋਰਸਮੈਂਟ', hi: 'लाइसेंस अनुमोदन',
    inspector: 'What license endorsement do you have for this type of work?',
    driver: 'I have a tanker and hazmat license endorsement, inspector.' },
  { category: 'legal_medical', en: 'Hazmat Endorsement', zh: '危险品背书', vi: 'chứng nhận chở hàng nguy hiểm', es: 'endoso de materiales peligrosos (hazmat)', pa: 'ਹੈਜ਼ਮੈਟ ਐਂਡੋਰਸਮੈਂਟ', hi: 'हैज़मैट अनुमोदन',
    inspector: 'Do you hold a current hazmat endorsement on your CDL?',
    driver: 'Yes, inspector, my hazmat endorsement is active and shown on the license.' },
  { category: 'legal_medical', en: 'Doubles/Triples Endorsement', zh: '双/三挂背书', vi: 'chứng nhận moóc đôi / ba', es: 'endoso de dobles / triples', pa: 'ਡਬਲ / ਟ੍ਰਿਪਲ ਟ੍ਰੇਲਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'डबल/ट्रिपल अनुमोदन',
    inspector: 'Do you have a doubles/triples endorsement to pull multiple trailers?',
    driver: 'Yes, inspector, my CDL includes a doubles/triples endorsement.' },
  { category: 'legal_medical', en: 'Tanker Endorsement', zh: '罐车背书', vi: 'chứng nhận xe bồn', es: 'endoso de cisterna (tanker)', pa: 'ਟੈਂਕਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'टैंकर अनुमोदन',
    inspector: 'Is a tanker endorsement required for the load you are hauling today?',
    driver: 'Yes, inspector, that is why I obtained the tanker endorsement last year.' },
  { category: 'legal_medical', en: 'Passenger Endorsement', zh: '客运背书', vi: 'chứng nhận chở khách', es: 'endoso de pasajeros', pa: 'ਪੈਸੇਂਜਰ ਐਂਡੋਰਸਮੈਂਟ', hi: 'यात्री अनुमोदन',
    inspector: 'Do you also have a passenger endorsement on your license?',
    driver: 'No, inspector, I do not have a passenger endorsement, only freight endorsements.' },

  // ── Documents / Permits ──────────────────────────────────
  { category: 'documents', en: 'RODS (Record of Duty Status)', zh: '值勤状态记录', vi: 'sổ ghi trạng thái làm việc', es: 'registro de estado de servicio (RODS)', pa: 'ਡਿਊਟੀ ਸਟੇਟਸ ਰਿਕਾਰਡ', hi: 'ड्यूटी स्थिति रिकॉर्ड (RODS)',
    inspector: 'Your ELD keeps your RODS, or Record of Duty Status, correct?',
    driver: 'Yes, inspector, all my RODS are stored in the ELD system.' },
  { category: 'documents', en: 'Fuel Receipts', zh: '燃油收据', vi: 'hóa đơn nhiên liệu', es: 'recibos de combustible', pa: 'ਫਿਊਲ ਰਸੀਦਾਂ', hi: 'ईंधन रसीदें',
    inspector: 'Where do you keep your fuel receipts for each load?',
    driver: 'I keep my fuel receipts in this envelope, inspector, and turn them in every week.' },
  { category: 'documents', en: 'Toll Receipts', zh: '过路费收据', vi: 'hóa đơn phí cầu đường', es: 'recibos de peaje', pa: 'ਟੋਲ ਰਸੀਦਾਂ', hi: 'टोल रसीदें',
    inspector: 'Do you save your toll receipts for company records?',
    driver: 'Yes, inspector, I save all toll receipts and attach them to my trip report.' },
  { category: 'documents', en: 'Scale Tickets', zh: '过磅单', vi: 'phiếu cân xe', es: 'boletas de báscula', pa: 'ਵਜ਼ਨ ਪੱਤਰ / ਸਕੇਲ ਟਿਕਟ', hi: 'तौल पर्ची',
    inspector: 'Please show me your scale tickets for this shipment.',
    driver: 'Here are the scale tickets, inspector, from when I weighed at the truck stop.' },
  { category: 'documents', en: 'Dispatch Records', zh: '调度记录', vi: 'hồ sơ điều phối', es: 'registros de despacho', pa: 'ਡਿਸਪੈਚ ਰਿਕਾਰਡ', hi: 'डिस्पैच रिकॉर्ड',
    inspector: 'Does dispatch keep detailed dispatch records for your loads?',
    driver: 'Yes, inspector, dispatch records every pickup and delivery in their system.' },
  { category: 'documents', en: 'Trip Sheets', zh: '行程单', vi: 'bảng hành trình / phiếu chuyến đi', es: 'hojas de viaje', pa: 'ਟ੍ਰਿਪ ਸ਼ੀਟ', hi: 'ट्रिप शीट',
    inspector: 'Do you fill out trip sheets for each run?',
    driver: 'Yes, inspector, I complete trip sheets with miles and stops for every load.' },
  { category: 'documents', en: 'GPS Data', zh: 'GPS数据', vi: 'dữ liệu GPS', es: 'datos de GPS', pa: 'GPS ਡਾਟਾ', hi: 'जीपीएस डेटा',
    inspector: 'Is your GPS data available if the company needs to check your route?',
    driver: 'Yes, inspector, my truck sends GPS data to our office in real time.' },
  { category: 'documents', en: 'Annual Inspection', zh: '年检报告', vi: 'báo cáo kiểm tra hàng năm', es: 'inspección anual', pa: 'ਸਾਲਾਨਾ ਜਾਂਚ ਰਿਪੋਰਟ', hi: 'वार्षिक निरीक्षण रिपोर्ट',
    inspector: 'Has this truck passed its required annual inspection?',
    driver: 'Yes, inspector, it passed the annual inspection last month.' },
  { category: 'documents', en: 'Permit Book', zh: '证件夹', vi: 'sổ / bìa đựng giấy phép', es: 'libro de permisos', pa: 'ਪਰਮਿਟ ਬੁੱਕ', hi: 'परमिट बुक',
    inspector: 'Where do you keep your permit book in the cab?',
    driver: 'My permit book is in this compartment above the driver seat, inspector.' },
  { category: 'documents', en: 'IFTA Permit', zh: 'IFTA许可', vi: 'giấy phép IFTA', es: 'permiso IFTA', pa: 'IFTA ਪਰਮਿਟ', hi: 'IFTA परमिट',
    inspector: 'Show me your IFTA permit, please.',
    driver: 'Yes, inspector, the IFTA permit is inside my permit book.' },
  { category: 'documents', en: 'IRP Registration', zh: 'IRP注册', vi: 'đăng ký IRP', es: 'registro IRP', pa: 'IRP ਰਜਿਸਟ੍ਰੇਸ਼ਨ', hi: 'IRP पंजीकरण',
    inspector: 'Do you have proof of your IRP registration in the truck?',
    driver: 'Yes, inspector, my IRP registration is printed on this cab card.' },
  { category: 'documents', en: 'Cab Card', zh: '车辆注册卡', vi: 'thẻ đăng ký xe (cab card)', es: 'tarjeta de cabina (cab card)', pa: 'ਕੈਬ ਕਾਰਡ', hi: 'कैब कार्ड',
    inspector: 'Is this the current cab card for this vehicle?',
    driver: 'Yes, inspector, this cab card matches the plate and VIN on the truck.' },
  { category: 'documents', en: 'Trailer Registration', zh: '挂车注册', vi: 'đăng ký rơ-moóc', es: 'registro del remolque', pa: 'ਟ੍ਰੇਲਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ', hi: 'ट्रेलर पंजीकरण',
    inspector: 'Can you show me the trailer registration for this unit?',
    driver: 'Here is the trailer registration, inspector, with the current year sticker.' },
  { category: 'documents', en: 'Insurance Certificate', zh: '保险证明', vi: 'giấy chứng nhận bảo hiểm', es: 'certificado de seguro', pa: 'ਬੀਮਾ ਸਰਟੀਫਿਕੇਟ', hi: 'बीमा प्रमाणपत्र',
    inspector: 'Do you have an insurance certificate for this vehicle?',
    driver: 'Yes, inspector, the insurance certificate is in my permit book.' },
  { category: 'documents', en: 'USDOT Number', zh: 'DOT编号', vi: 'số USDOT', es: 'número USDOT', pa: 'USDOT ਨੰਬਰ', hi: 'यूएसडीओटी नंबर',
    inspector: 'What is your company USDOT number?',
    driver: 'Our USDOT number is printed on the door and also here on the cab card, inspector.' },
  { category: 'documents', en: 'MC Number', zh: '运营编号', vi: 'số MC', es: 'número MC (operador)', pa: 'MC ਨੰਬਰ', hi: 'एमसी नंबर',
    inspector: 'What is your MC number for operating authority?',
    driver: 'Inspector, our MC number is listed right here on this document.' },
  { category: 'documents', en: 'Bill of Lading (BOL)', zh: '提单', vi: 'vận đơn', es: 'conocimiento de embarque (BOL)', pa: 'ਬਿਲ ਆਫ ਲੇਡਿੰਗ', hi: 'बिल ऑफ लेडिंग',
    inspector: 'Please hand me the Bill of Lading for this load.',
    driver: 'Yes, inspector, here is the Bill of Lading with the freight details.' },
  { category: 'documents', en: 'Hazmat Shipping Papers', zh: '危险品运输文件', vi: 'giấy tờ vận chuyển hàng nguy hiểm', es: 'documentos de envío de materiales peligrosos', pa: 'ਖਤਰਨਾਕ ਸਮਾਨ ਦੀਆਂ ਡਾਕੂਮੈਂਟਸ', hi: 'खतरनाक माल शिपिंग कागजात',
    inspector: 'Are you carrying any hazmat shipping papers today?',
    driver: 'No, inspector, I have no hazmat shipping papers because this load is not hazardous.' },
  { category: 'documents', en: 'Weight Ticket', zh: '重量单', vi: 'phiếu cân nặng', es: 'ticket de peso', pa: 'ਵਜ਼ਨ ਟਿਕਟ', hi: 'वजन टिकट',
    inspector: 'Can I see your latest weight ticket for this cargo?',
    driver: 'Here is the weight ticket from the scale I used this morning, inspector.' },
]
